### DISCUSSION TITLE
ESP32 XTAL configuration from Zephyr

### DISCUSSION THREAD

**Discussion by cederom** [zephyrproject-rtos/zephyr#36827] [Q&A] [answered]
Hello world :-)

It seems my custom board that I want to add support for Zephyr has different XTAL (24MHz) than set by default in IDF:
```
W (65) rtc_clk_init: Possibly invalid CONFIG_ESP32_XTAL_FREQ setting (40MHz). Detected 26 MHz.
```

I cannot run Hello World uart example - I get some console output from bootloader then trash but there is no expected output from the Zephyr code.. it looks like bootloader is waiting for DFU not launching the Zephyr application? Or the XTAL setting is invalid?

This setting is generated to `build/` and contained in `sdkconfig` file. How this file is generated and where are default parameters are taken from? `CONFIG_ESP32_XTAL_FREQ_AUTO` seems more universal default value.

Looks like this issue is described here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html#step-10-monitor. The question is how to "change CONFIG_ESP32_XTAL_FREQ_SEL to 26 MHz" from Zephyr standpoint without touching the `esp-idf` module and not using `idf.py`?

Any hints appreciated :-)

**Comment by cederom** [comment]
Hello @b0661, as you have experience with ESP32 custom board, do you know how to change XTAL from 40MHz to 26MHz for ESP32? That resides in `sdkconfig` in `build/`, but I how do I set it from my application / board definition level without touching the `hal_espressif` module? :-)

**Comment by cederom** [comment, marked as answer]
As explained here https://github.com/zephyrproject-rtos/hal_espressif/issues/38 by @sylvioalves this is `rtc` setting and can be adjusted in `dts`/`overlay` file with:
```
&rtc {
    xtal-freq = <ESP32_CLK_XTAL_26M>;
};
```

Note: `ESP32_CLK_XTAL_AUTO` is not yet supported but it is planned :-)

TANK U SIR!! =)

**Comment by bsingh19** [comment]
Getting started with Zephyr (Setup toolchain, compilation, board bring-up, Hello World example)!!

Systems: MacBook
Board : nRF52833 DK (Optional)

https://youtu.be/4emoE-8hsqg

**Comment by paveltyk** [comment]
1. Run `make menuconfig` or `idf.py menuconfig` in the project root
2. Goto "Component config" -> "ESP32-specific" -> "Main XTAL frequency"
3. Set to 26MHz
4. `idf.py flash monitor`

**Comment by darkofc** [comment]
Perhaps the above answers no longer work with some of the change made since then.   It seems that the cpu bindings file: dts/bindings/cpu/espressif,xtensa-lx6.yaml has xtal-freq enum values of 40Mhz and 32Mhz, but not 26Mhz.   Thus preventing us from selecting the necessary value.    The only way I've gotten things to work is to modify  the espressif,xtensa-lx6.yaml file to add the enum 2600000 and then add to my board's .dts file:

```
&cpu0 {
	xtal-freq = <DT_FREQ_M(26)>;
};
&cpu1 {
	xtal-freq = <DT_FREQ_M(26)>;
};
```

Currently espressif,xtensa-lx6.yaml has the enums defined as:

```
  xtal-freq:
    type: int
    required: true
    description: Value of the external XTAL connected to ESP32.
    enum:
      - 40000000
      - 32000000
```

Is this considered a bug/issue?  Or is there some way I can work around this in my board's configuration?
FYI: I'm trying to get zeyphr to work on a sparkfun "[thing](https://www.sparkfun.com/products/13907)" board.

Without setting this correctly I just get garbage output on the console - the initial bootup messages are okay, but then turns to garbage after the line:

W (85) rtc_clk_init: Possibly invalid CONFIG_XTAL_FREQ setting (40MHz). Detected 26 MHz.

**Comment by Philip-Kirner** [comment]
Hey @darkofc!

I found a potential work around for the enum limitations.

I found that I could create custom device tree bindings in my zephyr project, and by listing them first in the device tree `compatible` field, 26 MHz would be accepted as the configured xtal-freq!

```
example-application/
├─── app/
├─── boards/thing/
|      └── mbus_connectors.dtsi
└─── dts/bindings/
        └── expressif,xtensa-lx6-overlay.yaml
```

mbus_connectors.dtsi        
```
/ {	
	cpus {
		cpu0: cpu@0 {
			device_type = "cpu";
			compatible = "espressif,xtensa-lx6-overlay", "espressif,xtensa-lx6";
			reg = <0>;
			cpu-power-states = <&light_sleep &deep_sleep>;
			clock-source = <ESP32_CPU_CLK_SRC_PLL>;
			clock-frequency = <DT_FREQ_M(240)>;
			xtal-freq = <DT_FREQ_M(26)>;
		};

		cpu1: cpu@1 {
			device_type = "cpu";
			compatible = "espressif,xtensa-lx6-overlay", "espressif,xtensa-lx6";
			reg = <1>;
			clock-source = <ESP32_CPU_CLK_SRC_PLL>;
			clock-frequency = <DT_FREQ_M(240)>;
			xtal-freq = <DT_FREQ_M(26)>;
		};
	};
#...	
```

expressif,xtensa-lx6-overlay.yaml
```
description: Espressif Xtensa CPU on Sparkfun Thing board

compatible: "espressif,xtensa-lx6-overlay"

include: cdns,tensilica-xtensa-lx6.yaml

properties:
  xtal-freq:
      type: int
      required: true
      description: Value of the external XTAL connected to ESP32.
      enum:
        - 40000000
        - 32000000
        - 26000000
```
