### DISCUSSION TITLE
dts/bindings files for out-of-tree sensor driver is not being included build

### DISCUSSION THREAD

**Discussion by juliaoconnell-eaton** [zephyrproject-rtos/zephyr#45805] [Q&A] [answered]
Hi there, 

I am creating an out-of-tree sensor driver and have based my project structure on the [zephyr example-application](https://github.com/zephyrproject-rtos/example-application). I have included my devicetree binding file in dts/bindings folder. From analysing the build files, it seems that the **dts/bindings/** folder is not being included in the build. I have set the **DTS_ROOT** in both the _zephyr/module.yml_ and the root _CMakeLists.txt_ to no success.

As a result, when attempting to call **device_get_binding()** there is no binding in relation to the ATSENSE301 sensor and it returns NULL.

Project Structure
````
project
│   CMakeLists.txt
│   Kconfig
│   prj.conf
│   README.md
│   README.rst
│   west.yml
├───boards
│       stm32mp157c_dk2.conf
│       stm32mp157c_dk2.overlay
│
├───Code
│   │   CMakeLists.txt
│   │   Kconfig
│   │   main.cpp
│   │   main.h
│   │
│   └───drivers
│       │   CMakeLists.txt
│       │   Kconfig
│       │
│       └───ATSENSE301
│               ATSENSE301.cpp
│               ATSENSE301.h
│               CMakeLists.txt
│               Kconfig
│
├───dts
│   └───bindings
│           microchip,atsense301.yaml
│
└───zephyr
        module.yml
````

The output of my zephyr.dts.d file:
````
empty_file.o: C\:/Users/E0519648/zephyrproject/zephyr/misc/empty_file.c \
 C\:/zephyrproject/zephyr/boards/arm/stm32mp157c_dk2/stm32mp157c_dk2.dts \
 C\:/zephyrproject/zephyr/dts/arm/st/mp1/stm32mp157.dtsi \
 C\:/zephyrproject/zephyr/dts/common/mem.h \
 C\:/zephyrproject/zephyr/dts/common/freq.h \
 C\:/zephyrproject/zephyr/dts/arm/armv7-m.dtsi \
 C\:/zephyrproject/zephyr/dts/common/skeleton.dtsi \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/gpio/gpio.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/clock/stm32_clock.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/i2c/i2c.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/pwm/pwm.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/pwm/stm32_pwm.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/display/stm32_ltdc.h \
 C\:/zephyrproject/modules/hal/stm32/dts/st/mp1/stm32mp157cacx-pinctrl.dtsi \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/pinctrl/stm32-pinctrl.h \
 C\:/zephyrproject/zephyr/include/zephyr/dt-bindings/pinctrl/stm32-pinctrl-common.h \
 C\:/zephyrproject/zephyr/boards/arm/stm32mp157c_dk2/arduino_r3_connector.dtsi \
 C\:project/boards/stm32mp157c_dk2.overlay
````

I have attempted to set the DTS_ROOT in zephyr/module.yml:
````
build:
  cmake: .
  kconfig: Kconfig
  settings:
    board_root: .
    dts_root: .
`````

And in CMakeLists.txt in the root of the folder:
````
cmake_minimum_required(VERSION 3.20.0)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

project(mmplus_bl_rtos_app)

# Produce compile_commands.json
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_FLAGS "-fpermissive")

set(DTS_ROOT ${CMAKE_CURRENT_SOURCE_DIR})

include_directories("${ZEPHYR_BASE}/lib/libc/minimal/include")

add_subdirectory("Code" app)

target_sources(app PRIVATE
    "Code/main.cpp"
)
````
The microchip,atsense301.yaml file is as follows:
````
description: | 
  ATSENSE301, multi-channel analog front end devices seven A/D converters, voltage, current, 
  temperature sensor and an SPI interface. See more info at: 
  https://www.microchip.com/en-us/product/ATSENSE301
 
compatible: "microchip,atsense301"
 
include: spi-device.yaml
 
properties:
  reg:
    type: array
    required: true
  spi-max-frequency:
    type: int
    required: true
    description: Max freq of SPI communication
  frequency:
    type: int 
    required: true
    description: frequency of SPI communication
  label:
    type: string
    description: human-readable name
    required: true
 
````

And the stm32mp157c_dk2.overlay file is configured for SPI2:
````
&spi2 {
    status="okay";
    cs-gpios = <&gpioe 12 GPIO_ACTIVE_LOW>;
    pinctrl-0 = <&spi2_nss_pb12 &spi2_sck_pa9
             &spi2_miso_pb14 &spi2_mosi_pb15>;
    pinctrl-names = "default";  
    
    atsense301: atsense301@0 {
        compatible = "microchip,atsense301";
        status="okay";
        label = "ATSENSE301";
        reg = <0>;
        spi-max-frequency = <200000>;
        frequency = <40000>; 
    };   
};
````

The main.cpp file
````
#include <zephyr.h>
#include <device.h>
#include <devicetree.h>
#include "drivers/ATSENSE301/ATSENSE301.h"

#define ATSENSE301_DEV DT_NODELABEL(atsense301)
#if !DT_NODE_EXISTS(ATSENSE301_DEV)
#error "whoops"
#endif
/*
 *****************************************************************************************
 *		Functions
 *****************************************************************************************
 */

 /*
  * Get a device structure from a devicetree node with compatible
  * "microchip,atsense301"
  */
static const struct device *get_atsense301_device(void)
{
    const struct device *atsense301 = device_get_binding(DT_LABEL(ATSENSE301_DEV));

    if (atsense301 == NULL) {
        // No such node, or the node does not have status "okay"
        printk("\nError: no device found.\n");
        return NULL;
    }
    if (!device_is_ready(atsense301)) {
        printk("\nError: Device \"%s\" is not ready; "
               "check the driver initialization logs for errors.\n",
               atsense301->name);
        return NULL;
    }

    printk("Found device \"%s\", getting sensor data\n", atsense301->name);
    return atsense301;
}
````

In the ATSENSE301.cpp file, I have configured the DT_DRV_COMPACT:
````
#define DT_DRV_COMPACT microchip_atsense301
````
and the initialisation macro for the sensor is as follows:
````
#define ATSENSE301_DEFINE(n)								\
    static struct atsense301_data atsense301_data_##n;				\
    static const struct atsense301_config atsense301_config_##n = {	\
        .spi = SPI_DT_SPEC_INST_GET(n,							\
                        SPI_OP_MODE_MASTER |						\
                        SPI_WORD_SET(8U) |							\
                        SPI_TRANSFER_MSB,							\
                        0U),										        \
        .freq = DT_INST_PROP(n,frequency),						\
    };														\
    DEVICE_DT_INST_DEFINE(n, atsense301_init, NULL,				\
                  &atsense301_data_##n, &atsense301_config_##n,		\
                  POST_KERNEL, CONFIG_SENSOR_INIT_PRIORITY,		\
                  &atsense301_api);

DT_INST_FOREACH_STATUS_OKAY(ATSENSE301_DEFINE)
````
I am really struggling to understand what I am missing. 

Appreciate any help!
Thanks!
