### DISCUSSION TITLE
Can I use west to configure a CMake style in-repo but out-of-source setup?

### DISCUSSION THREAD

**Discussion by inkychris** [zephyrproject-rtos/zephyr#53872] [Q&A] [answered]
I was hoping I could get `west init` to download everything into a local git-ignored directory in my project, much like
```
cmake -S . -B .build
```
The `-l` option gets me close but dumps everything in the folder above which won't be viable when I move it to a self hosted Gitlab runner that has persistent build directories. I think the "free application" model is what I want, but I don't seem to have enough control over the output for my liking.

I have a west manifest in my project repo that I was hoping to use just to get the west command extensions and one module import (hal_espressif in this case). Maybe this is complicating things or there's a better way to achieve this? It's not looking like I can do what I want at least without moving the manifest into a separate repo which seems excessive given that it's describing the dependencies of the project source in the (currently) same repo.

Is this just how it is? I'm used to Python virtual environments and CMake, and this project structuring feels like I'm supposed to be developing in what I'm currently seeing as a build directory.

Thanks in advance!

**Comment by yashi** [comment, marked as answer]
A simple answer is "No.  West is designed to have a workspace".

With a scheme like Python virtual env, you can't have the [T3](https://docs.zephyrproject.org/3.1.0/develop/west/workspaces.html#t3-forest-topology) topology, which West is required to support.



You can have a `west.yml` just like the following to put everything under your project.  But, West still needs a workspace one above your project directory.  This puts all modules under your project directory.

```yml
manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        path-prefix: foo/modules/
        name-allowlist:
          - cmsis
          - hal_stm32
          - picolibc

  self:
    path: foo
```

You can run `west build` in your project directory (not confused with your workspace) without specifying `-d BUILD_DIR` or `source_dir`.  It puts all artifacts under `workspace/foo/build`. But West still needs a workspace.

This is what you end up with.
```
tree -a -L 5 /tmp/ws
/tmp/ws
├── .west
│   └── config
└── foo
    ├── modules
    │   ├── modules
    │   │   ├── hal
    │   │   │   ├── cmsis
    │   │   │   └── stm32
    │   │   └── lib
    │   │       └── picolibc
    │   └── zephyr
    │       ├── CMakeLists.txt
    │       :
    └── west.yml
```
