### DISCUSSION TITLE
Help understanding GPIO setup and configuation

### DISCUSSION THREAD

**Discussion by perowle** [zephyrproject-rtos/zephyr#59774] [Q&A]
Hi all,
Looking for advice on how to set up GPIOs for a project.  I've read through the documentation and experimented quite a bit, but still my solution seems like it'll be difficult to support, given that configuration for a GPIO is spread across multiple files (mostly the .dtsi and .c files), and I end up using a lot of memory of all the gpio_dt_spec structs.

First, I notice there's only a dt-binding for LEDs and Buttons, so I created gpio-generic.yaml, which just lets me create any GPIO without pre-supposing it's one of the pre-defined (LED,Button).  My yaml file is below.

Now, to define the GPIOs, I created a .dtsi (also below) for my board which groups the GPIO's by subsystem in my application (essentially by thread).
After doing this configuration, I have to go into my code, and for each gpio:
```
static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET_BY_IDX(DT_NODELABEL(greenled), gpios, 0);
static const struct gpio_dt_spec pb = GPIO_DT_SPEC_GET_BY_IDX(DT_NODELABEL(powerbutton), gpios, 0);



        if (!gpio_is_ready_dt(&led)) {
                return 0;
        }
        if (!gpio_is_ready_dt(&pb)) {
                return 0;
        }

        ret = gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);
        ret = gpio_pin_configure_dt(&pb, GPIO_INPUT);
```

then finally, I can
```
                gpio_pin_set_dt(&led, 0);
               
                gpio_pin_set_dt(&led, 1);
       if (gpio_pin_get_dt(&pb) == 1)
```

So questions:
      1) Is this the right way to manage GPIO's, or is there something simpler?
      2) What is the dt_flags member of the gpio_dt_spec structure used for? 
      3) Along those lines, why are the GPIO configuration symbols split between drivers/gpio.h and dt-bindings/gpio/gpio.h.  My initial thought was that I could set the pin configuration in the dtsi, and then use it in the code, this doesn't seem to be the case.

Thanks for any help understanding this - maybe I'm overcomplicating it.

Peter

**myboard_gpios.dtsi**
```

/ {
      subsystem1 {
            compatible = "gpio-generic";

            greenled: greenled {
                  gpios = <&gpioe 14 GPIO_ACTIVE_HIGH>;
            };

            powerbutton: powerbutton {
                  gpios = <&gpiob 5 GPIO_ACTIVE_HIGH>;
            };

            widget: widget {
                  gpios = <&gpiob 7 GPIO_ACTIVE_HIGH>;
            };
      };

      subsystem2 {
            compatible = "gpio-generic";

            yellowled: yellowled {
                  gpios = <&gpioc 3 GPIO_ACTIVE_HIGH>;
            };

            tp1: tp1 {
                  gpios = <&gpiob 8 GPIO_ACTIVE_HIGH>;
            };
      };
};


```

**gpio-generic.yaml**
```
description: |
  This allows you to create generic GPIO bindings

compatible: "gpio-generic"

child-binding:
  description: GPIO child node
  properties:
    gpios:
      type: phandle-array
      required: true
    label:
      type: string
      description: |
        Human readable string describing the GPIO
```
