### DISCUSSION TITLE
How to mount  a NVS partition automatically with NVS API?

### DISCUSSION THREAD

**Discussion by vChavezB** [zephyrproject-rtos/zephyr#60434] [Q&A] [answered]
I am using a static partition file with a section declared as follows:

```yaml
nvs_storage:
  address: 0x7b000
  end_address: 0x80000
  placement:
    align:
      start: 0x1000
    before:
    - end
  region: flash_primary
  size: 0x5000
```

From the [documentation](https://docs.zephyrproject.org/latest/services/storage/nvs/nvs.html) I did not find how I can refer to this partition for the initialization of a data struct of type `struct nvs_fs` which is required by the zephyr API `int nvs_mount(struct nvs_fs *fs)`.

I can manually initialize it by looking at the yaml file with the partition information but that would be double the work as zephyr already uses this information through the yaml file. Hence my question is if this can be done automatically by just pointing at the partition I want to use.
