### DISCUSSION TITLE
how to run -s command in twister

### DISCUSSION THREAD

**Discussion by carriegong** [zephyrproject-rtos/zephyr#63595] [Q&A]
dumb question maybe i am doing this wrong..
my testcase.yaml looks like this 
```
tests:
  unit.test:
    platform_allow:
      qemu_cortex_m3
 tags: unit
  integration.test:
    extra_dtc_overlay_files: some.overlay
```

so if i were to run unit.test scenario it would look something like `./scripts/twister -s path/to/unit.test`

i am getting 
  File "/opt/nordic/ncs/v2.4.0/zephyr/scripts/pylib/twister/twisterlib/testplan.py", line 172, in discover
    raise TwisterRuntimeError("No test cases found at the specified location...")
twisterlib.error.TwisterRuntimeError: No test cases found at the specified location...

runs fine with -T command...
