### DISCUSSION TITLE
Device Tree Error: Interrupt controller lacks binding while porting to visionfive2

### DISCUSSION THREAD

**Discussion by kanakshilledar** [zephyrproject-rtos/zephyr#64228] [Q&A]
Hello, I have created an issue linked to this discussion #64214 . I along with @pratikfarkase94 are working on porting visionfive2 to zephyr rtos. [Visionfive2](https://www.starfivetech.com/en/site/boards) is a RISCV based SBC based on JH7110 SoC ([full specifications](https://doc-en.rvspace.org/VisionFive2/Product_Brief/VisionFive_2/specification_pb.html)) 

There was a similar discussion #44137 regarding some similar lacks binding error but I am not able to solve it.

The source code for our work is in the branch [support_visionfive2](https://github.com/kanakshilledar/zephyr/tree/support_visionfive2) based off on zephyr-v3.5.0 branch. 
I am using the following command to build the `samples/hello_world` application
`$ west build -p always -b visionfive2_jh7110 samples/hello_world`

The following build logs I get
```
$ west build -p always -b visionfive2_jh7110 samples/hello_world/
-- west build: making build dir /home/kanak/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/kanak/zephyrproject/zephyr/samples/hello_world
-- CMake version: 3.22.1
-- Found Python3: /home/kanak/zephyrproject/.zephyr-env/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/kanak/.cache/zephyr
-- Zephyr version: 3.5.0 (/home/kanak/zephyrproject/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: visionfive2_jh7110
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found Dtc: /home/kanak/zephyr-sdk-0.16.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/kanak/zephyrproject/zephyr/boards/riscv/visionfive2_jh7110/visionfive2_jh7110.dts
devicetree error: interrupt controller <Node /soc/plic@c000000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> for <Node /soc/cache-controller@2010000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> lacks binding
-- In: /home/kanak/zephyrproject/zephyr/build/zephyr, command: /home/kanak/zephyrproject/.zephyr-env/bin/python3;/home/kanak/zephyrproject/zephyr/scripts/dts/gen_defines.py;--dts;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/home/kanak/zephyrproject/zephyr/dts/bindings;--header-out;/home/kanak/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.new;--edt-pickle-out;/home/kanak/zephyrproject/zephyr/build/zephyr/edt.pickle;--vendor-prefixes;/home/kanak/zephyrproject/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /home/kanak/zephyrproject/zephyr/cmake/modules/dts.cmake:279 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /home/kanak/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/kanak/zephyrproject/.zephyr-env/bin/python3 -B/home/kanak/zephyrproject/zephyr/build -GNinja -DBOARD=visionfive2_jh7110 -S/home/kanak/zephyrproject/zephyr/samples/hello_world
```

### Changes to sifive,s7.yaml
There were a lot of properties missing in the `dts/bindings/riscv/sifive,s7.yaml` file which were declared in `dts/riscv/starfive/jh7110.dtsi` file.
The following properties were added

```yaml
# Copyright (c) 2022 Shawn Nematbakhsh <shawn@rivosinc.com>
# SPDX-License-Identifier: Apache-2.0

description: SiFive S7 Standard Core CPU

compatible: "sifive,s7"

include: sifive-common.yaml

properties:
  d-cache-block-size:
    description: Specifies the block size in bytes of the data cache
    required: true
    type: int

  d-cache-sets:
    description: Specifies the number of associativity sets in the data cache
    required: true
    type: int

  d-cache-size:
    description: Specifies the size in bytes of the data cache
    required: true
    type: int

  d-tlb-sets:
    description: Specifies the number of entries in the data TLB
    required: true
    type: int

  d-tlb-size:
    description: Specifies the number of entries in the data TLB
    required: true
    type: int

  i-cache-block-size:
    description: Specifies the block size in bytes of the instruction cache
    required: true
    type: int

  i-cache-sets:
    description: Specifies the number of associativity sets in the instruction cache
    required: true
    type: int

  i-cache-size:
    description: Specifies the size in bytes of the instruction cache
    required: true
    type: int

  i-tlb-sets:
    description: Specifies the number of associativity sets in the instruction TLB
    required: true
    type: int

  i-tlb-size:
    description: Specifies the number of entries in the instruction TLB
    required: true
    type: int

  next-level-cache:
    description: Indicates that another level of cache exists
    required: true
    type: phandle

  tlb-split:
    description: Specifies that the TLB has a split configuration
    required: true
    type: boolean
 ```

## Steps to reproduce
```
$ git clone https://github.com/kanakshilledar/zephyr
$ cd zephyr
$ git checkout support_visionfive2
$ west build -p always -b visionfive2_jh7110 samples/hello_world
```

You should get the similar device tree related error.
Any solution on how can I solve this issue. I am fairly new to zephyr rtos and apologize if I miss anything.
If you need any more input from my side I am willing to share.

Thanks!
