### DISCUSSION TITLE
Device Tree Error: Interrupt Controller lacks binding . Porting for visionfive2

### DISCUSSION THREAD

**Discussion by kanakshilledar** [zephyrproject-rtos/zephyr#64235] [General]
I along with @pratikfarkase94 are working on adding support for visionfive2 board based on Starfive JH7110 SoC.
The source code to our work is in the branch support_visionfive2 based off on zephyr-v3.5.0 branch. 
I am using the following command to build the samples/hello_world application
`$ west build -p always -b visionfive2_jh7110 samples/hello_world`
Build logs
```
$ west build -p always -b visionfive2_jh7110 samples/hello_world/
-- west build: making build dir /home/kanak/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/kanak/zephyrproject/zephyr/samples/hello_world
-- CMake version: 3.22.1
-- Found Python3: /home/kanak/zephyrproject/.zephyr-env/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/kanak/.cache/zephyr
-- Zephyr version: 3.5.0 (/home/kanak/zephyrproject/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: visionfive2_jh7110
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found Dtc: /home/kanak/zephyr-sdk-0.16.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/kanak/zephyrproject/zephyr/boards/riscv/visionfive2_jh7110/visionfive2_jh7110.dts
devicetree error: interrupt controller <Node /soc/plic@c000000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> for <Node /soc/cache-controller@2010000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> lacks binding
-- In: /home/kanak/zephyrproject/zephyr/build/zephyr, command: /home/kanak/zephyrproject/.zephyr-env/bin/python3;/home/kanak/zephyrproject/zephyr/scripts/dts/gen_defines.py;--dts;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/home/kanak/zephyrproject/zephyr/dts/bindings;--header-out;/home/kanak/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.new;--edt-pickle-out;/home/kanak/zephyrproject/zephyr/build/zephyr/edt.pickle;--vendor-prefixes;/home/kanak/zephyrproject/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /home/kanak/zephyrproject/zephyr/cmake/modules/dts.cmake:279 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /home/kanak/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/kanak/zephyrproject/.zephyr-env/bin/python3 -B/home/kanak/zephyrproject/zephyr/build -GNinja -DBOARD=visionfive2_jh7110 -S/home/kanak/zephyrproject/zephyr/samples/hello_world
```

### Changes to sifive,s7.yaml
There were a lot of properties missing in the `sifive,s7.yaml` file which were declared in the `dts/riscv/starfive/jh7110.dtsi` file.
The following properties were added
```yaml
# Copyright (c) 2022 Shawn Nematbakhsh <shawn@rivosinc.com>
# SPDX-License-Identifier: Apache-2.0

description: SiFive S7 Standard Core CPU

compatible: "sifive,s7"

include: sifive-common.yaml

properties:
  d-cache-block-size:
    description: Specifies the block size in bytes of the data cache
    required: true
    type: int

  d-cache-sets:
    description: Specifies the number of associativity sets in the data cache
    required: true
    type: int

  d-cache-size:
    description: Specifies the size in bytes of the data cache
    required: true
    type: int

  d-tlb-sets:
    description: Specifies the number of entries in the data TLB
    required: true
    type: int

  d-tlb-size:
    description: Specifies the number of entries in the data TLB
    required: true
    type: int

  i-cache-block-size:
    description: Specifies the block size in bytes of the instruction cache
    required: true
    type: int

  i-cache-sets:
    description: Specifies the number of associativity sets in the instruction cache
    required: true
    type: int

  i-cache-size:
    description: Specifies the size in bytes of the instruction cache
    required: true
    type: int

  i-tlb-sets:
    description: Specifies the number of associativity sets in the instruction TLB
    required: true
    type: int

  i-tlb-size:
    description: Specifies the number of entries in the instruction TLB
    required: true
    type: int

  next-level-cache:
    description: Indicates that another level of cache exists
    required: true
    type: phandle

  tlb-split:
    description: Specifies that the TLB has a split configuration
    required: true
    type: boolean
```

## Steps to Reproduce
```
$ git clone https://github.com/kanakshilledar/zephyr
$ cd zephyr
$ git checkout support_visionfive2
$ west build -p always -b visionfive2_jh7110 samples/hello_world
```
You will get the similar device tree related error. 
Any solution on how can I solve this issue. I am fairly new to zephyr rtos and apologize if I miss anything.

Thanks!

**Comment by kanakshilledar** [comment]
If you are on zephyr v3.4.0 you may get a similar error to this one
```
$ west build -p always -b visionfive2_jh7110 samples/hello_world
usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] ...
west: unknown command "build"; do you need to run this inside a workspace?
```

I am not aware of any way to upgrade your existing west environment to the latest version of zephyr v3.5.0 (`west update` didnt help)

I created a new environment for west via `west init` and then cloned the repo and it worked. I am sure there might be any more efficient way than this one which i may not be aware of but for now it did the trick for me

**Comment by alpsayin** [comment]
I think similar is already mentioned at https://github.com/zephyrproject-rtos/zephyr/discussions/44137#discussioncomment-2464608
In this reply I'll hope to show you how you should be tracing it yourself:
```
devicetree error: interrupt controller <Node /soc/plic@c000000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> for <Node /soc/cache-controller@2010000 in '/home/kanak/zephyrproject/zephyr/misc/empty_file.c'> lacks binding
```
from your west build logs should tell everything that you need.
Searching for `plic@c000000` in your sources brings me to:
`dts/riscv/starfive/jh7110.dtsi:289` seems to set your plic's compatible to `riscv,plic0` which does not have a valid binding indeed.
You should read up about devicetrees and bindings if you're not yet acquainted (probably a good starting point: https://docs.zephyrproject.org/latest/build/dts/bindings-intro.html ) .
Plic is defined by riscv standards AFAIK, so I assume it **should** be safe to use the existing binding for it. 
Other riscv boards use: `sifive,plic-1.0.0` (suggested by `git grep -A 1 "interrupt-controller@c000000"`)
Changing the binding to `sifive,plic-1.0.0` then causes `gen_defines.py` to moan about interrupt-cells numbers (`dts/riscv/starfive/jh7110.dtsi:298`), which also probably should be changed to `2` (irq no and prio).
Then it's a completely different error about 
```
devicetree error: 'clock-frequency' is marked as required in 'properties:' in /zephyr/dts/bindings/flash_controller/cdns,qspi-nor.yaml, but does not appear in <Node /soc/spi@13010000 in '/zephyr/misc/empty_file.c'>
```
From there on, it's on you to follow up.
p.s. please don't take what I did as correct, please do your own due diligence.

**Comment by kanakshilledar** [comment]
I am now stuck at another devicetree error.
```
devicetree error: interrupt-names property in /soc/timer@13050000 in /home/kanak/zephyrproject/zephyr/misc/empty_file.c has 4 strings, expected 2 strings
```
This is the full build log. I am using the same build command as the one used above
```commandline
$ west build -p always -b visionfive2_jh7110 samples/hello_world/
-- west build: making build dir /home/kanak/zephyrproject/zephyr/build pristine
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/kanak/zephyrproject/zephyr/samples/hello_world
-- CMake version: 3.22.1
-- Found Python3: /home/kanak/zephyrproject/.zephyr-env/bin/python3 (found suitable version "3.10.12", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /home/kanak/.cache/zephyr
-- Zephyr version: 3.5.0 (/home/kanak/zephyrproject/zephyr)
-- Found west (found suitable version "1.1.0", minimum required is "0.14.0")
-- Board: visionfive2_jh7110
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found toolchain: zephyr 0.16.1 (/home/kanak/zephyr-sdk-0.16.1)
-- Found Dtc: /home/kanak/zephyr-sdk-0.16.1/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /home/kanak/zephyrproject/zephyr/boards/riscv/visionfive2_jh7110/visionfive2_jh7110.dts
devicetree error: interrupt-names property in /soc/timer@13050000 in /home/kanak/zephyrproject/zephyr/misc/empty_file.c has 4 strings, expected 2 strings
-- In: /home/kanak/zephyrproject/zephyr/build/zephyr, command: /home/kanak/zephyrproject/.zephyr-env/bin/python3;/home/kanak/zephyrproject/zephyr/scripts/dts/gen_defines.py;--dts;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/home/kanak/zephyrproject/zephyr/dts/bindings;--header-out;/home/kanak/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/home/kanak/zephyrproject/zephyr/build/zephyr/zephyr.dts.new;--edt-pickle-out;/home/kanak/zephyrproject/zephyr/build/zephyr/edt.pickle;--vendor-prefixes;/home/kanak/zephyrproject/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /home/kanak/zephyrproject/zephyr/cmake/modules/dts.cmake:279 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /home/kanak/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/kanak/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/home/kanak/zephyrproject/.zephyr-env/bin/python3 -B/home/kanak/zephyrproject/zephyr/build -GNinja -DBOARD=visionfive2_jh7110 -S/home/kanak/zephyrproject/zephyr/samples/hello_world
```

I have added the [starfive,jh7110-timer.yaml](https://github.com/kanakshilledar/zephyr/blob/support_visionfive2/dts/bindings/timer/starfive%2Cjh7110-timers.yaml) and the `interrupt-names` property contains 4 items:

```yaml

# ---- snip

  interrupts:
    items:
      - description: timer channel 0 interrupt
      - description: timer channel 1 interrupt
      - description: timer channel 2 interrupt
      - description: timer channel 3 interrupt
      
  interrupt-names:
    items:
      - const: timer0
      - const: timer1
      - const: timer2
      - const: timer3

  clocks:
    items:
      - description: timer channel 0 clock
      - description: timer channel 1 clock
      - description: timer channel 2 clock
      - description: timer channel 3 clock
      - description: APB clock
    
# ---- snip
```
The `interrupt-names` are defined in the `dts/riscv/starfive/jh7110.dtsi:476`

Any ideas on how can I solve this error?
Thanks
