### DISCUSSION TITLE
I2c Recovery Example application not available for STM32

### DISCUSSION THREAD

**Discussion by ShubhadaHarkut-eaton** [zephyrproject-rtos/zephyr#76492] [General]
I2c Recovery functions to prevent lockup is not used in any sample or driver code for stm32 controllers (stm32h743zi , stm32u575zi )

**Comment by ttmut** [comment]
I do not think that this should be considered a bug. Still, you could use I2C shell to test the recovery function.

**Comment by jhedberg** [comment]
@erwango any thoughts?

**Comment by ShubhadaHarkut-eaton** [comment]
Observations on I2C recovery api 
when using the recovery api from application n code it return the error stating the "SCL GPIO device not ready" . Tried creating a forceful lockup situation and called the recovery api after timeout faced the same results . 


Target used  stm32u575zi_q 
zephyr version : 3.6.0
os : windows

**Reply by erwango** [reply]
If not functional please raise an issue and provide a way to reproduce.

**Comment by ttmut** [comment]
According to the driver binding you need to define `scl-gpios` and `sda-gpios` if you want to use bus recovery.

https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/bindings/i2c/st%2Cstm32-i2c-v2.yaml

```yaml
 scl-gpios:
    type: phandle-array
    description: |
      GPIO to which the I2C SCL signal is routed. This is only needed for
      I2C bus recovery support.

 sda-gpios:
    type: phandle-array
    description: |
      GPIO to which the I2C SDA signal is routed. This is only needed for
      I2C bus recovery support.
```
