### DISCUSSION TITLE
twister: custom dts/bindings: can't load: <SchemaError: error code 2: Schema validation failed

### DISCUSSION THREAD

**Discussion by lexologe** [zephyrproject-rtos/zephyr#78609] [General] [answered]
I am trying to add a test to my project. The project has a custom board using default folder structure.
When I run
`west twister -T $(pwd)/tests/<component-dir> --board-root=$(pwd) -p <my-custom-board-name> --device-testing --device-serial /dev/ttyACM0 --device-serial-baud 115200`
I get this error for every of my custom dts/bindings yaml files.
```
ERROR   - E: <path-to-project>/dts/bindings/<vendor>,proximity-sensor.yaml: can't load: <SchemaError: error code 2: Schema validation failed:
 - Key 'description' was not defined. Path: ''.
 - Key 'include' was not defined. Path: ''.
 - Key 'compatible' was not defined. Path: ''.
 - Key 'properties' was not defined. Path: ''.: Path: '/'>
```
The DTS binding itself works fine, when I build the firmware. The head of the DTS looks like:
```
description: XYZ DTS bindings for proximity sensors

include: base.yaml

compatible: "<vendor>,proximity-sensor"

properties:
  gpios:
    required: true
    type: phandle-array
    description: |
      Text for description...
[..]
```
