### ISSUE TITLE
sanitycheck miss extra_args: OVERLAY_CONFIG parameter

### ISSUE THREAD

**Issue by finikorg** [zephyrproject-rtos/zephyr#13320]
**Describe the bug**
We have several `sample.yaml` for example in `samples/net/zperf/` with following overlay configuration:

```
  test_netusb_ecm:
    extra_args: OVERLAY_CONFIG="overlay-netusb.conf"
    extra_configs:
      - CONFIG_NET_TCP=n
      - CONFIG_SHELL_CMDS=n
    tags: usb net zperf
    depends_on: usb_device
```

For some reason sanitycheck misses all configuration from overlay files.

**To Reproduce**

sanitycheck -t zperf

**Expected behavior**
Should check with overlay config included

**Impact**
Does not test overlays
