### ISSUE TITLE
irq_connect_dynamic() is not tested on all arches

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#18276]
We have very little coverage of installing dynamic interrupts in test cases.

Even though gen_isr_tables.py is used on multiple arches, the test case for it is running only on ARM for some reason:

```
tests:
  arch.interrupt:
    platform_exclude: nucleo_f103rb olimexino_stm32 stm32_min_dev_black
        stm32_min_dev_blue usb_kw24d512 v2m_beetle
    filter: CONFIG_GEN_ISR_TABLES and CONFIG_ARMV7_M_ARMV8_M_MAINLINE
    tags: interrupt isr_table
```
Because of this, bugs like #18272 crept in.

We need to test dynamic IRQs on all arches that support it to show that they work.
