### ISSUE TITLE
addition to winbond,w25q16.yaml required for SPI CS to be controlled by driver

### ISSUE THREAD

**Issue by andyaoe** [zephyrproject-rtos/zephyr#19603]
if SPI_FLASH_W25QXXDV_GPIO_SPI_CS is selected in Kconfig.w25qxxdv, then the following 2 device tree variables are required in winbond,w25q16.yaml in order to compile the code

    cs-gpio-pin:
      type: int
      category: optional  
      description: Pin Number used for the CS Pin
      generation: define

    cs-gpio-controller:
      type: string
      category: optional
      description: Gpio Controller Used for the CS Pin
      generation: define

**Comment by ulfalizer** [comment]
Should now be this, to avoid warnings (see [this section in the devicetree manual](https://docs.zephyrproject.org/latest/guides/dts/index.html#legacy-binding-syntax)):

```
cs-gpio-pin:
    type: int
    required: false
    description: Pin number used for the CS pin

cs-gpio-controller:
    type: string
    required: false
    description: GPIO controller used for the CS pin
```
