### ISSUE TITLE
devicetree: sam0 gclk

### ISSUE THREAD

**Issue by sslupsky** [zephyrproject-rtos/zephyr#26617]
@galak @nzmichaelh I have been looking at the changes to the sam0 gclk framework.  I am curious if you plan to add some additional clock-cells or otherwise expand the configuration?  At the moment, the atmel,samd2x-gclk.yaml compat defines one clock cell for the clkctrl_id.

How do you propose to handle the other components of the gclk module (genctrl and gendiv)?  I have noticed that a few compatibles allow for assignment of a "clock-generator" (the sam0-rtc compat) or "gclk" (sam0-adc compat).  However, other elements of the gclk config are missing.

I created a compatible for the sam0 gclk configuration a while ago.  Here is a copy of that compatible.  This compatible lets you define the configuration of a particular gclk<n>.  Please let me know if you think this would be useful and I should submit this as a PR.

```
/*
 * Copyright (c) 2020 Scanimetrics Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

description: ATMEL GCLK (Generic Clock Controller)

compatible: "atmel,sam0-gclk"

include: [clock-controller.yaml, base.yaml]

child-binding:
    description:  GCLK child node
    properties:
        clock-generator:
            type: int
            required: false
            description: generic clock generator

        clock-source:
            type: int
            required: false
            description: generic clock generator source oscillator

        clock-standby:
            type: int
            required: false
            description: generic clock generator run in standby

        clock-divsel:
            type: int
            required: false
            description: generic clock generator divide selection

        clock-div:
            type: int
            required: false
            description: generic clock generator division factor

        clock-frequency:
            type: int
            description: output clock frequency (Hz)
            required: true

        label:
            required: true
            type: string
            description: Human readable string describing the device (used by Zephyr for API name)

```
