### ISSUE TITLE
sample for sensor lps22hh is not filtered out for bare nrf52dk_nrf52832

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#28059]
**Describe the bug**
The sample for sensor lps22hh is not filtered out for bare nrf52dk_nrf52832. I assume it requires a shield/sensor to be attached in the first place. It seems that using `fixture` in the sample.yaml could solve the problem. E.g. of how the sample.yaml could be modified:
```
...
    harness_config:
        fixture: x_nucleo_iks01a3
        type: multi_line
        ordered: yes
        regex:
            - "Temperature: (.*)"
            - "Pressure: (.*)"
```

**To Reproduce**
1. go to zephyr dir
2. run `./scripts/sanitycheck --device-testing -T samples/sensor/lps22hh/ -p nrf52dk_nrf52832 --device-serial /dev/ttyACM0 -v -v`
3. See failure of test

**Expected behavior**
The test is skipped when no shield provided

**Impact**
annoyance

**Logs and console output**
`DEVICE: Could not get LPS22HH device` and then fails with a timeout

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Toolchain Zephyr SDK 11.3
 - Commit SHA 4eba946e2b
