### ISSUE TITLE
Devicetree: Child node of node on SPI bus itself needs reg property - Bug?

### ISSUE THREAD

**Issue by arludwig** [zephyrproject-rtos/zephyr#30423]
**Disclaimer**
I am not sure this is actually a bug - it might just be that I have misunderstood some details about the devicetree. But it might also be a bug.

**Describe the bug**
I am trying to split the wiring and the protocol information of an spi slave device into two nodes. This would allow me to have a physical connector, like a zif-connector, on my board, hardwired to a specific chip select gpio; further more I would be able to specify the actual target device, like an epaper display, in an overlay file, specifying device dependent information, like the max frequency, clock configuration or word size. This way, I could support devices with different requirements by simply changing the overlay.

To achieve this, I define an `spi-target` binding for a node on an spi bus, that takes the actual device as child node. *Following example is simplified:*
```
description: SPI Target

compatible: spi-target

include: base.yaml

on-bus: spi

properties:
  reg:
    required: true

child-binding:
  description: SPI Device

  properties:
    spi-max-frequency:
      type: int
      required: true
      description: Maximum clock frequency of device's SPI interface in Hz
    
    label:
      type: string
      required: true
      description: Human readable string describing the device (used as device_get_binding() argument)
```
(Obviously I will have to write a custom driver for this, but I that is ok and not an issue here.)

I tested this with the following overlay file for a `nrf52840dk_nrf52840` board:
```
&spi3 {
    cs-gpios = <&arduino_header 16 GPIO_ACTIVE_LOW>; // D10

    spi_target@0 {
        compatible = "spi-target";
        reg = <0>;

        my_spi_dev_0 {
            label = "MY_DEVICE";
            spi-max-frequency = <10000000>;
        };
    };
};
```

When I try to apply this, I get the following error:
```
[cmake] Traceback (most recent call last):
[cmake]   File "C:\zephyrproject\zephyr\scripts\dts\gen_legacy_defines.py", line 827, in <module>
[cmake]     main()
[cmake]   File "C:\zephyrproject\zephyr\scripts\dts\gen_legacy_defines.py", line 55, in main
[cmake]     write_spi_dev(node)
[cmake]   File "C:\zephyrproject\zephyr\scripts\dts\gen_legacy_defines.py", line 534, in write_spi_dev
[cmake]     cs_gpio = node.spi_cs_gpio
[cmake]   File "C:\zephyrproject\zephyr\scripts\dts\edtlib.py", line 936, in spi_cs_gpio
[cmake]     _err("{!r} needs a 'reg' property, to look up the chip select index "
[cmake]   File "C:\zephyrproject\zephyr\scripts\dts\edtlib.py", line 2258, in _err
[cmake]     raise EDTError(msg)
[cmake] edtlib.EDTError: <Node /soc/spi@4002f000/spi_con@0/my_spi_dev_0 in 'nrf52840dk_nrf52840.dts.pre.tmp', binding .../dts/bindings\spi-target.yaml> needs a 'reg' property, to look up the chip select index for SPI
```

Seems zephyr requires the child node itself to have a `reg` property, which kind of defeats my intentions here.

**To Reproduce**
1. Define binding as above
2. Set overlay as above
3. CMake-configure the project
4. Read CMake output / error message

**Expected behavior**
When I have a device on the spi bus, then this device should be able to have itself children. So I would have expected my aproach to work. This would be a nice way to modularize devicetree information using overlays for mine and related cases.

**Impact**
This is more of an annoyance as a show stopper, because I can work around using non-related nodes and referring from the device to the `spi-target` via a `phandle` property. But from a devicetree structural point of view it would be a lot nicer (and I think also safer / less error prone) and clearer if a hierarchical structure could be used.

**Environment (please complete the following information):**
 - Windows 10
 - CMake 3.17.2
 - Zephyr 2.4 (c2a0b0f50bdb3c928e9d329cea93157e7cf0a469)
 - GNU ARM Embedded Toolchain (9 2020-q2-update)
