### ISSUE TITLE
devicetree: Allow child-binding bus controller without a need of compatible

### ISSUE THREAD

**Issue by kurddt** [zephyrproject-rtos/zephyr#32660]
Currently it's not possible to have a child-bindings acting as a bus controller unless there is a compatible property associated to it

Currently to describe an i2c mux one would need to create a binding like the following:
```
compatible: "ti,tca9546a"
include: "i2c-device.yaml"

properties:
    label:
        required: true
        type: string
        description: tca9546

child-binding:
    include: "i2c-controller.yaml"
    compatible: "ti,tca9546a-child"
    description: Downlink I2C bus tca9546
```

The child binding is only used as a placeholder and will probably not be used by the device driver but without it the child-binding is not taken as a bus controller

The following should be possible:
```
compatible: "ti,tca9546a"
include: "i2c-device.yaml"
properties:
    label:
        required: true
        type: string
        description: tca9546

child-binding:
    include: "i2c-controller.yaml"
    description: Downlink I2C bus tca9546
```
