### ISSUE TITLE
DTS binding create devicetree_unfixed.h build error at v2.7.0

### ISSUE THREAD

**Issue by lgl88911** [zephyrproject-rtos/zephyr#38675]
**Describe the bug**
I added the dts binding file and devicetree node, it compiles normally under v2.6.0, but fails to compile under 2.7.0-rc2.

**To Reproduce**
1. Add file dts/bindings/sensor/rotary-encoder.yaml
```
description: |
  Sensor driver for the relative-axis rotary encoder

compatible: "rotary-encoder"

properties:
  label:
    type: string
    required: true
  a-gpios:
    type: phandle-array
    required: true
    description: A pin for the encoder
  b-gpios:
    type: phandle-array
    required: true
    description: B pin for the encoder
  ppr:
    type: int
    description: Pulse Per Revolution
    required: false
  spp:
    type: int
    description: |
        Number of steps (stable states) per period
        1: Full-period mode (default)
        2: Half-period mode
        4: Quarter-period mode
    required: false
```
2. add node to board devicetree
```
input_encoder: rotary_encoder {
        compatible = "rotary-encoder";
        status = "okay";
        label = "INPUT_ENCODER";
        a-gpios = <&gpio1 22 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        b-gpios = <&gpio1 23 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>;
        ppr = <15>;
        spp = <2>;
};
```
3. Add driver file drivers/sensor/rotary_encoder/rotary_encoder.c
```
#define DT_DRV_COMPAT rotary_encoder

#include <device.h>
#include <drivers/gpio.h>
#include <drivers/sensor.h>
```
4. When I use west to build,See error
> /mnt/e/tomato/t-clock-master/build/zephyr/include/generated/devicetree_unfixed.h:723:39: error: expected ')' before string constant
  723 | #define DT_N_S_rotary_encoder_P_label "INPUT_ENCODER"

**Expected behavior**
Build Pass.

**Impact**
Can‘t migrate the Rotary encoder driver code from 2.6.0 to 2.7.0

**Additional context**
I check devicetree_unfixed.h:723:39， Everything seems to be normal, I don’t know why the compilation error occurs
```
#define DT_N_S_rotary_encoder_STATUS_okay 1

/* Pin control (pinctrl-<i>, pinctrl-names) properties: */
#define DT_N_S_rotary_encoder_PINCTRL_NUM 0

/* Generic property macros: */
#define DT_N_S_rotary_encoder_P_label "INPUT_ENCODER"
#define DT_N_S_rotary_encoder_P_label_STRING_TOKEN INPUT_ENCODER
#define DT_N_S_rotary_encoder_P_label_STRING_UPPER_TOKEN INPUT_ENCODER
```
