### ISSUE TITLE
intel_adsp_cavs25: west sign command output some unrecognized ASCII char.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#42098]
**Describe the bug**
for intel_adsp_cavs25 platform, when doing **west sign command, it reported some unrecognized ASCII char when parsing cse entry** name "cavs0015.met", the output as below, there are some unrecognized char after "cavs0015.met".
please ignore data of entry.offset and length, I removed them due to private policy.
```
 partition_name: 'ADSP'
         header_version: 2
          entry_version: 1
             nb_entries: 3
             entry.name: 'ADSP.man'
           entry.offset: 
           entry.length:
             entry.name: 'cavs0015.met▒'
           entry.offset: 
           entry.length: 
             entry.name: 'cavs0015'
           entry.offset: 
           entry.length: 
```
this will causing an **error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 899: invalid start byte" when using twister** command, because twister needs to decode the output string of "west flash" command.
the raw data of "west flash" captured by twister at position 899 as below, cannot decode \xc0\x04 using utf-8.
``` 
entry.name: 'cavs0015.met\xc0\x04'\n
```

**Debug Info**
I found that in tgl.toml file, there is a cse entry as below, the strlen(name) is 12 bytes,
```
[[cse.entry]]
name = "cavs0015.met"
offset = 
length = 
```
but the **cse entry definition in rimage source code is as below, the entry name is uint8 [12]**, it includes the empty char for string. so when **rimage parsing entry name "cavs0015.met", it just overlay the empty char**, then when we output this entry_name, it will output some other chars until meeting another empty char.
**so when we define a cse entry name, the max strlen(name) should be 11 chars, not 12 chars.**
```
struct CsePartitionDirEntry {
        uint8_t  entry_name[12];
        uint32_t offset;
        uint32_t length;
        uint32_t reserved;
}  __attribute__((packed));
```

**Suggestions**
**Could we using another name for cse entry "cavs0015.met", less than 12 chars**.
I tested this method, it worked well.

**Environment (please complete the following information):**
 - Zephyr Commit:  d51a67b7c098c
