### ISSUE TITLE
samples/mpu/mem_domain_apis_test is broken

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#4289]
Hi @chunlinhan , git shows you as the author of this sample.

There seem to be several issues with the sample "mpu/mem_domain_apis_test".

It's not clear which boards it should be compatible with, I'm not that great at reading these yaml fields,
but I tried with bbc_microbit and qemu_cortex_m3, and neither would build.

Usually I run sanitycheck on a sample to find out what boards it supports, but in this case
sanitycheck would not build it against any board. This is unfortunate, as it will be doomed to
suffer from bit rot.

AnaZ implied that the filter was incorrect, that it should be CONFIG_USERSPACE, I'm not sure how the filter field works.

```
<anaZ> Anas Nashif sebo_:
1:47 PM --- a/samples/mpu/mem_domain_apis_test/sample.yaml
1:47 PM +++ b/samples/mpu/mem_domain_apis_test/sample.yaml
1:47 PM @@ -5,5 +5,5 @@ tests:
1:47 PM  -   test:
1:47 PM          arch_whitelist: arm
1:48 PM          build_only: true
1:48 PM -        filter: USERSPACE
1:48 PM +        filter: CONFIG_USERSPACE
1:48 PM          tags: samples
1:48 PM sebo_:  i would open an issue and assign to Chunlin
1:48 PM it fails on nrf boards
```

```
sample:
    description: TBD
    name: TBD
tests:
-   test:
        arch_whitelist: arm
        build_only: true
        filter: USERSPACE
        tags: samples
```

To be specific
- This sample should build against the boards it is expected to work with.
- This sample should (I assume) be picked up by sanitycheck to prevent bit rot
