### ISSUE TITLE
it8xxx2_evb: tests/kernel/sched/schedule_api fail due to k_sleep(K_MSEC(100)) not correct

### ISSUE THREAD

**Issue by hunterhu3000** [zephyrproject-rtos/zephyr#46324]
**Describe the bug**
The daily test case tests/kernel/sched/schedule_api failed due to k_sleep(K_MSEC(100)) not correct, k_sleep is expected to wait 100ms, but actually it never ends.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?: it8xxx2_evb
 - What have you tried to diagnose or workaround this issue? Add log before and after k_sleep(K_MSEC(100)), the log after it is never seen

**To Reproduce**
Two ways to reproduce the behavior:
Method 1
1. twister -v -p it8xxx2_evb --device-testing --west-flash="../../itetool/loader.sh" --device-serial=/dev/ttyUSB0 -T tests/kernel/sched/schedule_api
Method 2
1. west build -p always -b it8xxx2_evb tests/kernel/sched/schedule_api -DCONFIG_TIMESLICE_PER_THREAD=y -DCONFIG_TIMESLICING=y
2. sudo -S ~/itetool/ite -f build/zephyr/zephyr.bin -s check

**Expected behavior**
The test can pass

**Impact**
Blocks all the daily tests under tests/kernel/sched/schedule_api

**Logs and console output**
Logs for west:
```
*** Booting Zephyr OS build zephyr-v3.1.0-514-gf232db463078  (delayed boot 1ms) ***
Running TESTSUITE threads_scheduling
===================================================================
START - test_bad_priorities
 PASS - test_bad_priorities in 0.1 seconds
===================================================================
START - test_priority_cooperative
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): ubuntu
 - Toolchain (e.g Zephyr SDK, ...): 0.14.1
 - Commit SHA or Version used: f875d027a04374fcf07661809f81a42c2c646629

**Comment by RuibinChang** [comment]
Why do you enable CONFIG_TIMESLICE_PER_THREAD?
it8xxx2_evb default isn't set this config.

**Comment by hunterhu3000** [comment]
> Why do you enable CONFIG_TIMESLICE_PER_THREAD? On it8xxx2_evb, default doesn't set this config.

One of the test case defined in the testcase.yaml contains this parameter
```
  kernel.scheduler.slice_perthread:
    filter: not CONFIG_SCHED_MULTIQ
    extra_configs:
      - CONFIG_TIMESLICING=y
      - CONFIG_TIMESLICE_PER_THREAD=y
    tags: kernel threads sched userspace ignore_faults
```
If you use west build without -DCONFIG_TIMESLICE_PER_THREAD=y, the case also fails.

**Comment by RuibinChang** [comment]
@hunterhu3000
I update the SDK to latest version v0.14.2 on commit https://github.com/zephyrproject-rtos/zephyr/commit/b9e833366f1360ecbad8776d6e8587e180688e1b, the 10 times result of kernel k_sleep() are pass.

**Comment by RuibinChang** [comment]
Running `west build -p always -b it8xxx2_evb tests/kernel/sched/schedule_api` on SDK v0.14.2 and commit f232db463078ff3e8a85ceeb9e9fcc0c14e141e3, the 10 times result of schedule_api are pass.

**Comment by hunterhu3000** [comment]
@RuibinChang
Sorry for late reply
Twist and west are different. When using twister to do the test, it will test many different configurations, but for west, it conly contains 1 most common config. For example the test case of tests/kernel/sched/schedule_api, there are 8 test cases defined in tests/kernel/sched/schedule_api/testcase.yaml. There are 7 test cases suitable for it8xxx2_evb. Among these 7, only 1 is failed. I copy the failed test below
```
  kernel.scheduler.slice_perthread:
    filter: not CONFIG_SCHED_MULTIQ
    extra_configs:
      - CONFIG_TIMESLICING=y
      - CONFIG_TIMESLICE_PER_THREAD=y
    tags: kernel threads sched userspace ignore_faults
```
As you can see, this case defined two more macros, so if you want to test it in west you need to add these macros, like this:
```
west build -p always -b it8xxx2_evb tests/kernel/sched/schedule_api -DCONFIG_TIMESLICE_PER_THREAD=y -DCONFIG_TIMESLICING=y
```

If you think any of these macros does not fit for it8xxx2_evb, or we do not need to test these macros, we can skip this test for it8xxx2_evb.
