### ISSUE TITLE
Sensor Subsystem: Base sensor DTS bindings

### ISSUE THREAD

**Issue by yperess** [zephyrproject-rtos/zephyr#48148]
We should come to an agreement on the following properties:

1, `label` should not be required, it's being phased out of Zephyr overall

2. `sensor-index` should not be specified by the application, it's assigned by the subsystem and should not be guaranteed to be the same across builds. Having to specify this manually makes it difficult to add/remove new entries in the middle.

3. `vendor`, `model`, and `friendly-name` should not be required at the individual node level, it's vulnerable to having a mismatch. Since there will be one node per sensor type here, several nodes may point to a single physical sensor.

4. I'm not sure why `minimal-interval` needs to be specified here. It's a component of the physical driver and can be attained through the sensor API.

5. `rotation-matrix` like `vendor` etc should not be here either, a physical sensor may have multiple of these nodes (1 per type) and this is likely to cause errors.

PROPOSAL

1. Remove label, there's no use for it

2. Remove `sensor-index` it should be assigned by the subsystem using `DT_` macros

3. Create a new binding for sensor metadata with all fields marked as optional. Many applications may not even have a UI and reporting the vendor/model/friendly-name is useless to them. The only required field is the sensor phandle and it should map to an existing HW sensor which we're describing.
```
properties:
  vendor:
    type: string
    required: false
  model:
    type: string
    required: false
  friendly-name:
    type: string
    required: false
  rotation-matrix:
    type: array
    required: false
  sensor:
    type: phandle
    required: true
```

4. Remove minimal interval, it's also not needed.
