### ISSUE TITLE
twister: testplan: toolchain_exclude filter is overridden by integration_platforms

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#49696]
**Describe the bug**

When both `integration_platforms` and `toolchain_exclude` are specified for a test, the twister testplan logic fails to apply the `toolchain_exclude` filter.

For example (8e8b56881feb9ed68b3435aa67436abc8a2a8b0f):
```yaml
  logging.add.log_user:
    tags: logging
    filter: CONFIG_USERSPACE
    extra_args: CONF_FILE=log_user.conf USERSPACE_TEST=1
    integration_platforms:
      - qemu_x86
    # FIXME: log_user test fails when compiled with the GCC 12 from Zephyr SDK.
    #        (see the GitHub issue zephyrproject-rtos/zephyr#49213)
    toolchain_exclude: zephyr
```

The `status` of the above test for `qemu_x86` is set to `error` (`In test case toolchain exclude but is one of the integration platforms`) instead of `filtered` -- this results in the CI attempting to run this test when it should not.

**To Reproduce**

At 8e8b56881feb9ed68b3435aa67436abc8a2a8b0f, run the following:

```
scripts/twister --integration --save-tests test.json
```

`test.json` contains the following:

```
        {
            "name":"tests/subsys/logging/log_core_additional/logging.add.log_user",
            "arch":"x86",
            "platform":"qemu_x86",
            "run_id":"d463ea458733a7bf02d91c8f39cc0cb8",
            "runnable":true,
            "status":"error",
            "reason":"In test case toolchain exclude but is one of the integration platforms",
            ...
```

**Expected behavior**

`status` for `tests/subsys/logging/log_core_additional/logging.add.log_user` on `qemu_x86` is set to `filtered`.

**Impact**

CI attempts to execute these tests because they are not "filtered."

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: Zephyr SDK 0.15.0
 - Commit SHA: 8e8b56881feb9ed68b3435aa67436abc8a2a8b0f

**Additional context**

Related discussion on Discord: https://discord.com/channels/720317445772017664/733037944922964069/1014173813795209216
