### ISSUE TITLE
Keeping "non-regural" binaries

### ISSUE THREAD

**Issue by gopiotr** [zephyrproject-rtos/zephyr#56192]
**Describe the bug**
In some cases names of built binaries differ from regular "zephyr.hex" names.

For example in tfm samples:
```
./scripts/twister -vv --inline-logs -T samples/tfm_integration/tfm_psa_test -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage -p nrf5340dk_nrf5340_cpuapp_ns --build-only
```
generated hex name is `tfm_merged.hex`:
`twister-out/nrf5340dk_nrf5340_cpuapp_ns/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage/tfm_merged.hex`

When I would like to use `--runtime-artifact-cleanup` then Twister remove  `tfm_merged.hex` and keep `zephyr.hex` file, what is undesirable. After applying: 
```
./scripts/twister -vv --inline-logs -T samples/tfm_integration/tfm_psa_test -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage -p nrf5340dk_nrf5340_cpuapp_ns --prep-artifacts-for-testing
```
There is no more `tfm_merged.hex` and then when I would like to run Twister with `--test-only` option, Twister is not able to flash properly binaries files (because `tfm_merged.hex` was removed).

---

Moreover, when `zephyr/runnres.yaml` contains absolute paths, then after applying `--prep-artifacts-for-testing` Twister remove beginning of those paths:
```
./scripts/twister -vv --inline-logs -T samples/tfm_integration/tfm_psa_test -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage -p nrf5340dk_nrf5340_cpuapp_ns --prep-artifacts-for-testing
```
Fragment of `runnres.yaml`:
```yaml
config:
  board_dir: /home/redbeard/zephyrproject/zephyr/boards/arm/nrf5340dk_nrf5340
  # Build outputs:
  elf_file: zephyr.elf
  hex_file: twister-out/nrf5340dk_nrf5340_cpuapp_ns/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage/tfm_merged.hex
  bin_file: zephyr.bin
```
After run Twister with `--test-only` option:
```
./scripts/twister -vv --inline-logs -T samples/tfm_integration/tfm_psa_test -s samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage -p nrf5340dk_nrf5340_cpuapp_ns --device-testing --device-serial /dev/ttyACM2 --test-only --west-flash
```
west is not able to find file like ` twister-out/nrf5340dk_nrf5340_cpuapp_ns/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage/tfm_merged.hex`

So, Twister should replace in `zephyr/runnres.yaml` absolute paths from absolute to relative paths (before applying sanitizing of zephyr base paths).

**Expected behavior**
 Twister should read information from `zephyr/runnres.yaml` file about which binaries files should be kept:
```yaml
config:
  board_dir: /home/redbeard/zephyrproject/zephyr/boards/arm/nrf5340dk_nrf5340
  # Build outputs:
  elf_file: zephyr.elf
  hex_file: /home/redbeard/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage/tfm_merged.hex
  bin_file: zephyr.bin
```
And then during sanitizing paths replace absolute path by relative one:
from:
`hex_file: /home/redbeard/zephyrproject/zephyr/twister-out/nrf5340dk_nrf5340_cpuapp_ns/samples/tfm_integration/tfm_psa_test/sample.tfm.psa_test_internal_trusted_storage/tfm_merged.hex`
to:
`hex_file: ../tfm_merged.hex`

**Impact**
I'm not able to call Twister once with `--prep-artifacts-for-testing` and secondly with `--test-only` options for `tfm` samples (and in any other situations when output binary file differ from `zephyr.hex` file). 

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: zephyr-sdk-0.15.0
 - Commit SHA: 1009b9152aa1f2dd3c6bca4401fd01c032aa1e79

**Additional context**
Proposition of fix: https://github.com/zephyrproject-rtos/zephyr/pull/56185
