### ISSUE TITLE
mcumgr: Probably misses "pending" flag, while reproting image list, for application that will be reverted

### ISSUE THREAD

**Issue by de-nordic** [zephyrproject-rtos/zephyr#56581]
**Describe the bug**
MCUmgr reports following flags for slots: `active`, `confirmed` and `pending`, where
 - `active` means that this is running slot
 - `confirmed` means that application image is confirmed (by user via remote command or by internal app tests)
 - `pending` which means that image in this slot will be boot next

When slots are listed by MCUmgr with confirmed application in primary slot, the output looks like this:
```
Images:
 image=0 slot=0
    version: 1.0.0.1
    bootable: true
    flags: active confirmed
    hash: a703bb7696391346aafaad983f1b23b290fb514cdc4644a78d8185a1e0fc2382
 image=0 slot=1
    version: 2.0.0.2
    bootable: true
    flags:
    hash: cec6b32da3269014159548178ec300b382fbad96784957c481a49ad57e8e9124
```
which means that `slot0` is `active` (application is running from it) and application is considered validated.
`slot1` does not have any flags, because none are set yet.

Now when secondary slot will be set for test the output, before reset, will look like this:
```
Images:
 image=0 slot=0
    version: 1.0.0.1
    bootable: true
    flags: active confirmed
    hash: a703bb7696391346aafaad983f1b23b290fb514cdc4644a78d8185a1e0fc2382
 image=0 slot=1
    version: 2.0.0.2
    bootable: true
    flags: pending
    hash: cec6b32da3269014159548178ec300b382fbad96784957c481a49ad57e8e9124
```

which makes sense, because now the secondary slot will be the one to be boot (`pending`), which does not take away the fact that `slot0` is still running (`active`) and valid (`confirmed`).

After reboot we got:
```
Images:
 image=0 slot=0
    version: 2.0.0.2
    bootable: true
    flags: active
    hash: cec6b32da3269014159548178ec300b382fbad96784957c481a49ad57e8e9124                                                                                                                                                                                                         image=0 slot=1
    version: 1.0.0.1                                                                                                                                                                                                                                                                  bootable: true
    flags: confirmed
    hash: a703bb7696391346aafaad983f1b23b290fb514cdc4644a78d8185a1e0fc2382
```

Where we can see that nobody has yet confirmed the running slot (it is `active`) and the secondary slot is `confirmed`, because it is app that has been previously `confirmed` in primary slot. The device is now in "test" mode, which means that unless user confirms application in primary slot, the secondary slot will be swapped in its place next boot - this means that secondary slot should be reporting `pending`  flag, as it will be next to boot.

**To Reproduce**
TBD

**Expected behavior**

**Impact**
Just seems inconsistent. Question is whether this should be fixed? Logically it makes sense, but may be problematic for existing software that is already used to current behavior.

**Environment (please complete the following information):**
 - Visible on Zephyr f8d747f85c7f7b2768d2395016b411686cefafa2
 - Toolchain and host system independent
