### ISSUE TITLE
samples: drivers :adc  error in main.c  printk issue with twister test

### ISSUE THREAD

**Issue by Desvauxm-st** [zephyrproject-rtos/zephyr#56845]
Describe the bug

our twister test sample/drivers/adc  with all board are failed
due to the modification into sample/drivers/adc/src/main.c
in line 58:
printk("ADC reading[%u]:\n", count++);

The output on the console is no longer aligned with what is written in the sample.yaml
boards: all board
the bug is due to the PR  sensor: Add NTC thermistor sensor for TDK Robokit1 board #54947

Signed-off-by: Marc Desvaux <marc.desvaux-ext@st.com>

To Reproduce
lunch any test in console with 

Expected behavior
our twister test sample/drivers/adc  with all board must be pass
and
The output on the console must be  aligned with what is written in the sample.yaml
boards: all board

Impact
 our twister test sample/drivers/adc  with all board are failed

Logs and console output
```
*** Booting Zephyr OS build zephyr-v3.3.0-2587-g9d041dd6f2d3 ***
ADC reading[0]:
- adc@40022000, channel 0: 3601 = 181 mV
ADC reading[1]:
- adc@40022000, channel 0: 2463 = 124 mV
```

Environment (please complete the following information):

OS: (e.g. Linux,)
Toolchain (ZEPHYR SDK 0.15.2)
SHA1 : 6d192e50cf7f8cb6c2a611b32c856136b3655982

Additional context
@asemjonovs
 the bug is due to the PR  sensor: Add NTC thermistor sensor for TDK Robokit1 board #54947

I suggest to change the sample.yaml with something like that ( remove : after "ADC reading )
before :
 ```
         tests:
            sample.drivers.adc:
              *****
                type: multi_line
                regex:
                  - "ADC reading:"                 

```
after :
```
          tests:
            sample.drivers.adc:
              *****
                type: multi_line
                regex:
                  - "ADC reading"

```
