### ISSUE TITLE
snippets: Possibility to include multiple overlay files in one snippet

### ISSUE THREAD

**Issue by maciejbaczmanski** [zephyrproject-rtos/zephyr#57581]
**Is your enhancement proposal related to a problem? Please describe.**
Right now, only one `DTC_OVERLAY_FILE` and `OVERLAY_CONFIG` can be added per snippet, which in some cases requires creating multiple snippets.
For example, while building low power mode application for power consumption measurements from nRF OpenThread CLI sample (https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/protocols/thread/overview/power_consumption.html#openthread-power-consumption) , requires adding: `-- -DOVERLAY_CONFIG="overlay-ci.conf;overlay-low_power.conf" -DDTC_OVERLAY_FILE="low_power.overlay"`. It would be nice to replace it with one snippet, e.g. `-S low_power`. 

**Describe the solution you'd like**
 Above problem could be solved by changing `snippets.py` file and `snippet-schema.yml` to accept list of strings instead of just one string and creating a snippet this way:
```
name: low_power
    append:
      OVERLAY_CONFIG:
        - overlay-ci.conf
        - overlay-low_power.conf
      DTC_OVERLAY_FILE:
        - low_power.overlay
```

**Describe alternatives you've considered**
We can create multiple snippets for now, but proposed enhancement could make the process easier.

@mbolivar-nordic @stephanosio @carlescufi
