### ISSUE TITLE
Expand Device Tree enums to C-enum names

### ISSUE THREAD

**Issue by DaGuich** [zephyrproject-rtos/zephyr#59256]
**Is your feature request related to a problem? Please describe.**
While creating the device tree bindings and implementing the parsing of the said bindings, we came across some issues. 
In the pre-zephyr times, we had the configuration of these devices in code, with an enum, where every enum value was associated with either direct register values or bit masks to work on the registers. 
At the moment we are using included defines inside of the device tree in combination with int-enums in the device tree bindings to reflect this. But from our point of view this has some disadvantages:

- The device tree binding (yaml) gets cluttered with lots of hard-to-understand integer values
- The value/bit mask is in distributed at least 2 times in the project (dt-bindings and header file)
- The generated device tree file gets harder to read and "debug"

Instead of using in the dt-bindings an integer enum, we could use a string enum. Then we are able to access the enum value by using the props `..._ENUM_TOKEN` macro.

The string enum will be easier to read in the generated device tree. It will also not generate any overhead in the binaries as these are behind macros in `devicetree_generated.h`. But this also has some drawbacks. First and foremost the configuration will have the full code-enum value which (again) makes the device tree harder to read. 

Example:
Configuration of a multiplier:
Enumeration: 
```
enum devname_pwm_multiplier_t {
    DEVNAME_MULT_8 = 0x00,
    DEVNAME_MULT_10 = 0x10,
    DEVNAME_MULT_38 = 0x50,
    DEVNAME_MULT_44 = 0x60,
    DEVNAME_MULT_48 = 0x70,
};
```

dt-bindings:
```
properties:
  pwm-multiplier:
    type: int
    enum:
      - 0
      - 16
      - 80
      - 96
      - 112
    description: useful description
```

**Describe the solution you'd like**

The addition necessary for this is a macro to prefix (and maybe postfix) the string enum with the actual code-enum value. 

Using the example above
dt-bindings
```
properties:
  pwm-multiplier:
    type: string
    enum:
      - "MULT_8"
      - "MULT_10"
      - "MULT_38"
      - "MULT_44"
      - "MULT_48"
    description: useful description
```

In code, we would have a macro to access it

```
  .pwm_multiplier = DT_INST_ENUM_PREFIX(n, pwm_multiplier, DEVNAME_),
```

The macro `DT_INST_ENUM_PREFIX` will expand then to `DEVNAME_MULT_38` 

**Describe alternatives you've considered**
An alternative solution would have been to add an additional field(s) in the device-tree syntax which would contain the code-enum prefix and postfix. For this, we would also need to adapt the scripts to generate additional macros into `devicetree_generated.h`.
