### ISSUE TITLE
twister/sysbuild: `extra_config` gives malformed Kconfig if `sysbuild: true` in sample.yaml

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#59843]
**bug description**
In the twister build extra_config paramiters gives malformed Kconfig while this is used along with the sysbuid.

For instance for fallowing sampe.yaml file
``` yaml
tests:
  sample.sysbuild_extra_config.faill
    sysbuild: true
    platform_allow: nrf5340dk_nrf5340_cpuapp
    integration_platforms:
      - nrf5340dk_nrf5340_cpuapp
    extra_configs:
      - CONFIG_CONSOLE=n
```

twister will fail on `warning: ignoring malformed line 'CONFIG_CONSOLE=n`

**To Reproduce**
Use extra_config in twister build along with sysbuild.

**Expected behavior**
extra_config should be transfer to the build similar as for simple builds.

**Impact**
annoyance.
Looks like we can use `extra_args` instead, but this is apparently a bug.

**Environment (please complete the following information):**
