### ISSUE TITLE
tests/kernel/mem_protect/x86_mmu_api: crashes on Arduino_101

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#6424]
Test at test/kernel/mem_protect/x86_mmu_api lead to CPU page fault when run on Arduino_101. Please refer the log below:

Yaml file specifies arduino_101 and qemu_x86 as whitelist. The test passes on qemu_x86.
```
tests:
       kernel.memory_protection.mmu:
       platform_whitelist: qemu_x86 arduino_101
       tags: kernel

```
 ```
***** BOOTING ZEPHYR OS v1.10.99 (delayed boot 1000ms) - BUILD: Mar  2 2018 04:52:20 *****
 Running test suite userbuffer_validate
 ===================================================================
 starting test - test_buffer_rw_read
 ***** CPU Page Fault (error code 0xfdf30003)
 Supervisor thread wrote address 0xa800c030
 PDE: 0x027 Present, Writable, User
 PTE: 0x221 Present, Read-only, Supervisor
 Current thread ID = 0xa8007060
 Faulting segment:address = 0x0008:0x400110d7
 eax: 0xa800c000, ebx: 0xa800c000, ecx: 0x00000006, edx: 0x00001000
 esi: 0xa800c030, edi: 0xa800c227, ebp: 0xa8007628, esp: 0xa8007618
 eflags: 0x10286
 Fatal fault in thread 0xa8007060! Aborting.
```
