### ISSUE TITLE
Allow include mechanism in yaml happens on all level

### ISSUE THREAD

**Issue by LSChyi** [zephyrproject-rtos/zephyr#64669]
## Introduction

In the [documentation](https://docs.zephyrproject.org/3.3.0/build/dts/bindings-syntax.html#include) of using include in yaml, it states that:

> Included files are merged into bindings with a simple recursive dictionary merge. The build system will check that the resulting merged binding is well-formed. It is allowed to include at any level, including child-binding

, so people would expect the include mechanism could take effects on any place, and the included yaml file is merged into that binding level, yet current [implementation](https://github.com/zephyrproject-rtos/zephyr/blob/9b851b2ab813b0bca588f0afeff7d5e878c0e789/scripts/dts/python-devicetree/src/devicetree/edtlib.py#L272) only expands the include on:

1. Under root node.
2. Under child-binding node.

### Problem description

As we use yaml to limit the available properties and allowed value in the dts, we found it causes lots of repetition when a type of enum is used in different files, here is an example:

I have different types of LED driver:

- GPIO LED
- PWM LED
- one-wire driven LED (such as ws2812)

, and all three LED drivers have an enum field `led-name`. Under current implementation, I can only compose yaml files as below:

```
compatible = "vnd,gpio-led-driver"

properties:
  led-name:
    type: string
    enum:
      - LED_ID_BATTERY
      - LED_ID_POWER
```

```
compatible = "vnd,pwm-led-driver"

properties:
  led-name:
    type: string
    enum:
      - LED_ID_BATTERY
      - LED_ID_POWER
```

```
compatible = "vnd,one-wire-led-driver"

properties:
  led-name:
    type: string
    enum:
      - LED_ID_BATTERY
      - LED_ID_POWER
```

, which causes lots of repetition.

It is not possible to define  a separate yaml file with shared enum with a yaml anchor, then include that file under root level, because PyYAML complains that missing yaml anchor:

```
compatible = "vnd,gpio-led-driver"
include: "common_led_enum.yaml" # <- a separate yaml file that holds the anchor &led_enum_name
properties:
  led-name:
    type: string
    enum: *led_name_enum # <- PyYAML failed right after loading this yaml file, because the alias *led_name_enum does not exist
```

### Proposed change

If the `include` is expanded on all levels, we could refactor the example above:

Define the enum type in a separate file `led_name_enum.yaml`:

```
enum:
  - LED_ID_BATTERY
  - LED_ID_POWER
```

, then include that file, where the content of `led_name_enum.yaml` is expected to be merged:

```
compatible = "vnd,one-wire-led-driver"

properties:
  led-name:
    type: string
    include: "led_name_enum.yaml"
```

## Detailed RFC

The proposed change should only involves changes inside the `scripts/dts/python-devicetree/src/devicetree/edtlib.py`, which expands all include node.

### Proposed change (Detailed)

We would pre-process all include node and call `_merge_includes` to expand and merge it right after loading, recurrsivly. The merged yaml is then hand over for following processings. As a result, all existing validation code get an expanded, standard yaml content, and thus no change is required for following yaml processing code, and these processing code should work as before.

### Dependencies

Should only depends on python scripts that process yaml files.

### Concerns and Unresolved Questions

In the proposed change, each enum type would require a separate yaml file. If there are *N* enum type, *N* yaml files are needed.

## Alternatives

This alternative is mainly for solving *N* enum type would require *N* yaml files. If we allow multiple enum types define in a single file, and we can reference needed enum via yaml anchor, we would have less files

```
compatible = "vnd,gpio-led-driver"
include: "common_led_enum.yaml" # <- a separate yaml file that holds many yaml anchor, including the anchor &led_enum_name
properties:
  led-name:
    type: string
    enum: *led_name_enum # <- alias that references anchor from included common_led_enum.yaml
```

However, this means we either need to:

1. Modify PyYAML code to allow it to load yaml with missing yaml anchor.
2. Pre-process and expand yaml files before hand over to PyYAML.

Both seems involving more changes, and some changes even occurs in other projects, so probably it is better to stick with the proposed approach.
