### ISSUE TITLE
Implement the path binding type

### ISSUE THREAD

**Issue by hadrienk** [zephyrproject-rtos/zephyr#69970]
The type `path` described in the documentation is ignored/unimplemented in the device tree generation. 
 
Given a binding: 

```yaml
description: |
  Foo

compatible: "bar"

properties:
  test:
    type: path
    required: true
```

and a dts that looks like: 

```dts
/ {
  anode0: node_0 {};
  test0: test_0 {
    test: &anode0
  };
};
``` 
The property is not defined in the generated dts. The only available definition is: 

```c
#define DT_N_S_test_0_P_test_EXISTS 1
`
