### ISSUE TITLE
HWMv2: cpuclusters property in soc/<vendor>/soc.yml file vs cpucluster property in boards/<vendor>/board.yml file

### ISSUE THREAD

**Issue by dbaluta** [zephyrproject-rtos/zephyr#71446]
**Describe the bug**

Documentation says that `cpuclusters` property is defined in soc's soc.yml file and shouldn't be present in board.yml.

Anyhow, it looks like a property `cpucluster` is found in board.yml file for some boards.

What is the difference between `cpuclusters` and `cpucluster`?

e.g


```
$ cat soc/nxp/imx/soc.yml

family:
- name: nxp_imx
  series:
  - name: imx8
  - name: imx8m
    socs:
    - name: mimx8ml8
      cpuclusters:
      - name: adsp
      - name: a53
      - name: m7
```
vs

```
$ cat boards/imx8mp_evk/board.yml

board:                                                                                                                                                                                                             
  name: imx8mp_evk
  vendor: nxp
  socs:
  - name: mimx8ml8
    variants:
    - name: smp
      cpucluster: a53
    - name: ddr
      cpucluster: m7
 
```

Also, Documentation list the following board.yml pseudo schema:

```
board:
  name: <board-name>
  vendor: <board-vendor>
  revision:
    format: <major.minor.patch|letter|number|custom>
    default: <default-revision-value>
    exact: <true|false>
    revisions:
    - name: <revA>
    - name: <revB>
      ...
  socs:
  - name: <soc-1>
    variants:
    - name: <variant-1>
    - name: <variant-2>
      variants:
      - name: <sub-variant-2-1>
        ...
  - name: <soc-2>
    ...

```

which doesn't contain cpucluster property

**Comment by nordicjm** [comment]
For board.yml files it is to add variants, so for the above:
```
  - name: mimx8ml8
    variants:
    - name: smp
      cpucluster: a53
    - name: ddr
      cpucluster: m7
```
This adds a smp variant to the a53 cluster, and a ddr variant to the m7 cluster, it does not add the clusters themselves
