### ISSUE TITLE
The west boards command fails when adding boards and socs in out-of-tree mode

### ISSUE THREAD

**Issue by foxriver1025** [zephyrproject-rtos/zephyr#71761]
**Describe the bug**
The west boards command fails when adding boards and socs in out-of-tree mode.
This error can be fixed by modifying the zephyr/scripts/west_commands/boards.py file.
In function 'do_run' add this codes:
```
for module in zephyr_module.parse_modules(ZEPHYR_BASE, self.manifest):
    soc_root = module.meta.get('build', {}).get('settings', {}).get('soc_root')
    if soc_root is not None:
        args.soc_roots.append(Path(module.project) / soc_root)
```
So I think the west boards command did not take into account that soc_root needs to be found in zephyr_module, and board_root has already done this.

**To Reproduce**
My workspce is as follows:
```
m88star5_work
├── m88star5-sdk
│   ├── app
│   ├── boards
│   │     └── montage-tech
│   │		└── qemu_tps
│   │			├── board.cmake
│   │			├── board.yml
│   │			├── doc
│   │			│   └── index.rst
│   │			├── Kconfig
│   │			├── Kconfig.defconfig
│   │			├── Kconfig.qemu_tps
│   │			├── qemu_tps_defconfig
│   │			├── qemu_tps.dts
│   │			└── qemu_tps.yaml
│   ├── CMakeLists.txt
│   ├── drivers
│   ├── dts
│   ├── include
│   ├── Kconfig    
│   ├── README.md
│   ├── soc
│   │	└── montage-tech
│   │		├── CMakeLists.txt
│   │		├── Kconfig
│   │		├── Kconfig.defconfig
│   │		├── Kconfig.soc
│   │		├── m88star5
│   │		│   ├── CMakeLists.txt
│   │		│   ├── common_linker
│   │		│   │   └── init.ld
│   │		│   ├── Kconfig
│   │		│   ├── Kconfig.defconfig
│   │		│   ├── Kconfig.defconfig.m88star5
│   │		│   ├── Kconfig.soc
│   │		│   ├── l2_cache.c
│   │		│   ├── linker.ld
│   │		│   ├── pma.c
│   │		│   ├── soc_context.h
│   │		│   ├── soc_irq.S
│   │		│   ├── soc_offsets.h
│   │		│   ├── soc_v5.h
│   │		│   └── start.S
│   │		└── soc.yml
│   ├── west.yml
│   └── zephyr
└── zephyr
```
I add a board named 'qemu_tps' and a soc named 'm88star5'.
The code in boards/montage-tech/qemu_tps/board.yml is as follows:
```
board:
  name: qemu_tps
  vendor: qemu
  socs:
    - name: m88star5
```
And the code in soc/montage-tech/soc.yml is as follows:
```
family:
- name: m88star5-family
  series:
  - name: m88star5
    socs:
    - name: m88star5
```
Then I used the west boards command and the following error occurred：
`ERROR: SoC 'm88star5' is not found, please ensure that the SoC exists and that soc-root containing 'm88star5' has been correctly defined.`

**Expected behavior**
The west boards command can list custom boards named 'qemu_tps'.

**Impact**
I cannot use the west boards command to list custom boards

**Logs and console output**
`ERROR: SoC 'm88star5' is not found, please ensure that the SoC exists and that soc-root containing 'm88star5' has been correctly defined.`

**Environment (please complete the following information):**
 - OS: (Ubuntu 22.04.3 LTS)
 - Toolchain (Zephyr SDK 0.16.3)
 - Commit SHA lastest

**Comment by nordicjm** [comment]
Where is your `zephyr/module.yml` file that has e.g.
```
build:
  settings:
    board_root: .
    soc_root: .
```
?

**Comment by foxriver1025** [comment]
@nordicjm The file is in _m88star5-sdk/zephyr/module.yml_, as follows:
```
name: m88star5-sdk
build:
  kconfig: Kconfig
  cmake: .
  settings:
    board_root: .
    dts_root: .
    soc_root: .
    #module_ext_root: .
samples:
  - samples
tests:
  - tests
boards:
  - boards
```
