### ISSUE TITLE
snippets: Add support for variants

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#76361]
**Is your enhancement proposal related to a problem? Please describe.**
In order for a set of related features to be supported using snippets, we need to create multiple snippets and copy the base overlays and add specific feature overlays, this again adds duplication.

**Describe the solution you'd like**
Introduce the concept of variants using base and extended overlays, where a single snippet folder can have multiple sub-snippets with  a base snippet, an example `snippets.yaml`

`snippets/debug_wifi/snippets.yml`
```
base_name: wifi_debug
append:
  EXTRA_CONF_FILE: overlay-base-debug.conf

variant_suffix: supplicant
append:
  VARIANT_OVERLAY_FILE: overlay-supp-debug.conf

variant_suffix: driver
append:
  VARIANT_OVERLAY_FILE: overlay-driver-debug.conf
```

* Debugging driver: `-DSNIPPET=wifi_debug_driver`
* Debugging supplicant: `-DSNIPPET=wifi_debug_supplicant`
* Generic Wi-Fi debug: `-DSNIPPET=wifi_debug`

`VARIANT_OVERLAY_FILE` is an overlay and we use standard Zephyr overlay rules to generate final overlay.

**Describe alternatives you've considered**
Have separate snippets and copy the overlays and extend/modify as per snippet.

**Additional context**
NA
