### ISSUE TITLE
input: stm32 touch sensing controller peripheral implementation

### ISSUE THREAD

**Issue by arifbalik** [zephyrproject-rtos/zephyr#79126]
### Problem description

Some STM32 models have [TSC peripheral](http://www.st.com/resource/en/product_training/stm32l4_peripheral_touchsense.pdf) for capacitive touch sensing applications, this really accelerates application development and Zephyr has no support for it yet.

### Proposed change

I want to implement this hardware in input subsystem.

## Detailed RFC

There is no LL file for this peripheral and it is a rather simple peripheral to work with. Most of the devices has almost identical registers and configuration. So my plan is to create a unified `st,stm32-tsc.yaml` binding to define and control this peripheral.

I will be pushing the group capture values (readings from the sensing channels) to input subsystem so anyone can pick it up after it is enabled. 

There is also [STM32 Tocuh Library](https://www.st.com/en/embedded-software/32l1-touch-lib.html) but I am not planning to use it in this implementation as it is pretty high level and wouldn't pass zephyr coding guidelines.

### Proposed change (Detailed)

I already sketched out an initial binding file you can see below;

My configuration pretty much includes all available settings this peripheral can have;

-  Charge transfer pulse high/low duration
- Spread spectrum (enable/disable deviation and prescaler)
- Pulse generator prescaler
- Max count feature (count value and interrupt settings)
- Default io modes (push-pull or floating)
- Sync mode (enable and polarity)

These settings belong to the parent node which applies to all groups. Then each sensing channel is a child node and has the following properties;

- Schmitt trigger mode
- Analog mode
- Channel type (sampling cap or electrode)

```yaml
# dts/bindings/input/st,stm32-tsc.yaml

description: STM32 Tocuh Sensing Controller (TSC) driver

compatible: "st,stm32-tsc"

include: [base.yaml, pinctrl-device.yaml]

properties:
  resets:
    type: phandle-array
    description: Reset controller

  cpth:
    type: int
    default: 1
    description: |
      Duration of the high state of the 
      charge transfer pulse (charge of Cx).
    enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

  cptl:
    type: int
    default: 1
    description: |
      Duration of the low state of the 
      charge transfer pulse (transfer of charge from CX to CS).
    enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

  ssd:
    type: int
    default: 0
    description: Spread spectrum deviation ([6:0] bits)

  spread-spectrum:
    type: boolean
    description: Spread spectrum enable

  spread-spectrum-prescaler:
    type: boolean
    description: Spread spectrum prescaler (fhclk/2 if enabled)

  pgpsc:
    type: int
    default: 1
    description: Pulse generator prescaler
    enum: [1, 2, 4, 8, 16, 32, 64, 128]

  mcv:
    type: int
    description: Max count value
    enum: [255, 511, 1023, 2047, 4095, 8191, 16383]

  iodef:
    type: string
    default: "push-pull-low"
    description: |
      I/O Default mode. Configuration of TSC IO when no acquisition is ongoing.
    enum: ["push-pull-low", "input-floating"]

  syncpol:
    type: string
    default: "falling-edge"
    description: Synchronization pin polarity.
    enum: ["falling-edge", "rising-edge"]

  synced-acquisition:
    type: boolean
    description: Synchronized acquisition enable (acquisition starts when START bit and signal on sync pin)

child-binding:
  description: STM32 TSC group configuration
  schmitt-trigger-hysteresis:
    type: boolean
    description: Schmitt trigger hysteresis enable

  analog-switch:
    type: boolean
    description: Analog switch enable

  channel-type:
    type: string
    default: "normal"
    description: Channel type
    enum: ["sampling", "normal"]
```

Here is an exmaple node for STM32U0x series;

```devicetree
tsc : tsc@40024000 {
            compatible = "st,stm32-tsc";
            reg = <0x40024000 0x400>;
            clocks = <&rcc STM32_CLOCK_BUS_AHB1 0x01000000>;
            resets = <&rctl STM32_RESET(AHB1, 24U)>;
            interrupts = <21 0>;
            status = "disabled";
        };

&tsc {
  status = "okay";
  cpth = <1>;
  cptl = <1>;
  ssd = <0>;
  spread-spectrum;
  spread-spectrum-prescaler;
  pgpsc = <1>;
  mcv = <255>;
  iodef = "push-pull-low";
  synced-acquisition;
  syncpol = "falling-edge";

  channel@0 {
    channel-type = "sampling";
    pinctrl-0 = <&tsc_ch0>;
    pinctrl-names = "default";
  };

  channel@1 {
    channel-type = "normal";
    analog-switch;
    pinctrl-0 = <&tsc_ch1>;
    pinctrl-names = "default";
  };

}
```

### Concerns and Unresolved Questions

- I'm not sure if the child node should represent a group or an individual channel. Maybe people from ST can help with that.
- All devices with TSC only has 1 of this peripheral, I'm not sure whether i should implement is as a single instance per device or not.
