### ISSUE TITLE
west: blobs fetch

### ISSUE THREAD

**Issue by WilliamGFish** [zephyrproject-rtos/zephyr#84085]
**West blobs fetch failure**

When attempting to retrieve blobs using the west command receive an error.

https://github.com/zephyrproject-rtos/mbedtls/pull/61
(https://github.com/zephyrproject-rtos/mbedtls/pull/61/files#diff-27d260b3de385946dc5c56da8181a3a9d4f5897cfab9df6dc2f5bb56bb0bbd6f)
zephyr/module.yml
```
build:
  cmake-ext: True
  kconfig-ext: True
security:
  external-references:
    - cpe:2.3:a:arm:mbed_tls:3.6.1:*:*:*:*:*:*:*
    - pkg:github/Mbed-TLS/mbedtls@V3.6.1
```

By reversing PR61
The west functionality works as expected

**To Reproduce**

```
\zephyr>west blobs fetch hal_infineon
ERROR: Malformed "build" section in file: /zephyr/modules/crypto/mbedtls/zephyr/module.yml
<SchemaError: error code 2: Schema validation failed:
 - Key 'security' was not defined. Path: ''.: Path: '/'>
```

**Expected behaviour**
Retrieval of the defined files/blobs.

**Logs and console output**

> \zephyr>west blobs fetch hal_infineon
> ERROR: Malformed "build" section in file: C:/Users/BillyBob/zephyrGoodX/modules/crypto/mbedtls/zephyr/module.yml
> <SchemaError: error code 2: Schema validation failed:
>  - Key 'security' was not defined. Path: ''.: Path: '/'>

**Environment**

 - OS: Windows
 - Toolchain Zephyr SDK
