### ISSUE TITLE
cmake: yaml: issues with strings containing special chars

### ISSUE THREAD

**Issue by pillo79** [zephyrproject-rtos/zephyr#87765]
**Describe the bug**

The YAML module fails to properly handle strings containing double quotes, especially when generator expressions are involved due to the multiple passes required. 

**To Reproduce**

Build the `llext-edk` target for a WiFi shell sample on the `frdm_rw612` board:

```
west build -p -b frdm_rw612 samples/net/wifi/shell -t llext-edk -- -DCONFIG_LLEXT_EDK=y
```

The `cflags` entry in the resulting `build/build_info.yml` is clearly partial / broken:

  ```
  cmake:
    ...
    llext-edk:
      cflags:
       - -D$<JOIN:KERNEL
       - __ZEPHYR__=1
       - __LINUX_ERRNO_EXTENSIONS__
       - PICOLIBC_DOUBLE_PRINTF_SCANF
       - BOARD_FLASH_SIZE=CONFIG_FLASH_SIZE*1024
       - __PROGRAM_START
       - CPU_RW612ETA2I
       - RW610
       - WIFI_BT_TX_PWR_LIMITS=
  ```

The section ends here because `WIFI_BT_TX_PWR_LIMITS` defines a string with quotes, which break the YAML processing (and also some internal genexes, see the first entry). 

**Expected behavior**

With PR #87752 applied, this is the expected result:

```
cmake:
  ...
  llext-edk:
    cflags:
     - '-DKERNEL'
     - '-D__ZEPHYR__=1'
     - '-D__LINUX_ERRNO_EXTENSIONS__'
     - '-DPICOLIBC_DOUBLE_PRINTF_SCANF'
     - '-DBOARD_FLASH_SIZE=CONFIG_FLASH_SIZE*1024'
     - '-D__PROGRAM_START'
     - '-DCPU_RW612ETA2I'
     - '-DRW610'
     - '-DWIFI_BT_TX_PWR_LIMITS="wlan_txpwrlimit_cfg_WW_rw610.h"'
     - '-DK_HEAP_MEM_POOL_SIZE=51200'
       ...
```

**Impact**

Cannot generate the EDK for some targets and/or config combinations 

**Environment (please complete the following information):**

Happens on fully updated current `main` (9207a1bcd77).
