### ISSUE TITLE
dts: uart-controller: Missing <mark> and <space> in parity enum

### ISSUE THREAD

**Issue by mrcamilletti** [zephyrproject-rtos/zephyr#88199]
**Is your enhancement proposal related to a problem? Please describe.**
The DTS binding file `uart-controller.yaml` only considers `none`, `odd` and `even` options for parity, however the UART API `drivers/uart.h` also considers "mark" and "space" in `enum uart_config_parity` (`UART_CFG_PARITY_MARK`, `UART_CFG_PARITY_SPACE`).  

**Describe the solution you'd like**
Modify the `dts/bindings/serial/uart-controller.yaml` file to extend the enumerator options as defined in the UART API `enum uart_config_parity`.

```yaml
  parity:
    type: string
    description: |
      Configures the parity of the adapter. Enumeration id 0 for none, 1 for
      odd, 2 for even, 3 for mark (forced 1) and 4 for space (forced 0)
      parity. Default to none if not specified.
    enum:
      - "none"
      - "odd"
      - "even"
      - "mark"
      - "space"
    default: "none"
```

**Describe alternatives you've considered**
Other alternative is to use a different property in device bindings for those that support `mark` and `space` parity. 

**Additional context**
We're currently developing a driver for SC16IS752 (UART over I2C/SPI bus) that supports "mark" and "space" features and we discovered this was missing in the UART controller binding. We would like to contribute this driver in the near future.
