### ISSUE TITLE
build_info.yml not properly regenerated on non-pristine builds

### ISSUE THREAD

**Issue by edersondisouza** [zephyrproject-rtos/zephyr#88324]
**Describe the bug**
`build_info.yml` is not properly regenerated on non-pristine builds (those without `-p`). Essentially, this causes it to contain, instead of expected data, commented-out cmake yaml lists (used to handle cmake generator expressions[genexes]). It seems like, after `build_info.yml` exists, target `build_info_yaml_saved` is never run again. However, new builds may update its contents, possibly with genexes, but they won't be properly converted.

This incomplete `build_info.yml` then breaks EDK generation, as it depends on it.

**To Reproduce**

```
west build -p -b qemu_cortex_r5 samples/subsys/llext/edk/app
touch samples/subsys/llext/edk/app/CMakeLists.txt 
west build -b qemu_cortex_r5 samples/subsys/llext/edk/app
```
Note that in my tests, the changes need to involve the build system. Not sure if there are other changes that can trigger this.

See that the generated `build_info.yml` has something like this:

```
(...)
  llext-edk:
#   cflags: @YAML-LIST@;-D$<JOIN:KERNEL$<SEMICOLON>__ZEPHYR__=1$<SEMICOLON>(...)
    file: /home/ederson/work/zephyr/zephyr-west/zephyr/build/zephyr/llext-edk.tar.xz
#   include-dirs: @YAML-LIST@;$<TARGET_PROPERTY:zephyr_interface,INTERFACE_INCLUDE_DIRECTORIES>
  toolchain:
    name: zephyr
(...)
```

**Expected behavior**
A completely generated `build_info.yml`.

**Impact**
Annoyance. Time wasted. Higher energy costs? Warmer planet?
One can workaround that by 1) sticking to pristine builds or 2) removing `build_info.yml` before a new build. Still annoying.

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain Zephyr SDK 0.17.0
 - Latest main (ddedff71557552ed6c4cb88ce14299217111f482)
