### ISSUE TITLE
West Build: Issues on UF2 based bootloader boards with MCUBOOT and Sysbuild

### ISSUE THREAD

**Issue by joaodullius** [zephyrproject-rtos/zephyr#88802]
I'm working with the **Seeed Studio XIAO BLE Sense** board, which comes with an **Adafruit UF2 bootloader** located at **0xF4000**. This bootloader expects to jump to an application at **0x27000**.

My goal is to make **this bootloader coexist with MCUBOOT**, eliminating the need for an external SWD programmer. This approach could be extended to other UF2-compatible boards, and possibly even to BOSSA-compatible boards such as those from Arduino.

The idea is to **retain the original Adafruit bootloader**, which will then jump either directly to the application or to MCUBOOT at 0x27000.

**Scenario 1: No MCUBOOT and no Sysbuild**
In this setup, Zephyr generates the final zephyr.uf2 from zephyr.hex, correctly respecting the image size defined in the board's device tree (.dts).
**Result:** The UF2 file can be successfully flashed using the Adafruit bootloader.*

**Scenario 2: MCUBOOT and no Sysbuild**
n this case, I had to add a pm_static.yml to guide partition manager (PM) to place the partitions correctly:

```yaml
sd_partition:
  address: 0x00000
  end_address: 0x27000
  region: flash_primary
  size: 0x27000

mcuboot:
  address: 0x27000
  end_address: 0x33000
  region: flash_primary
  size: 0xC000

mcuboot_pad:
  address: 0x33000
  end_address: 0x33200
  placement:
    align:
      start: 0x1000
    before:
      - mcuboot_primary_app
  region: flash_primary
  size: 0x200

app:
  address: 0x33200
  end_address: 0x8F000
  region: flash_primary
  size: 0x5BE00

mcuboot_primary:
  address: 0x33000
  end_address: 0x8F000
  orig_span: &id001
    - mcuboot_pad
    - app
  region: flash_primary
  sharers: 0x1
  size: 0x5C000
  span: *id001

mcuboot_primary_app:
  address: 0x33200
  end_address: 0x8F000
  orig_span: &id002
    - app
  region: flash_primary
  size: 0x5BE00
  span: *id002

mcuboot_secondary:
  address: 0x8F000
  end_address: 0xEB000
  region: flash_primary
  size: 0x5C000
  placement:
    after:
      - mcuboot_primary
    align:
      start: 0x1000
    align_next: 0x1000

gap:
  address: 0xEB000
  end_address: 0xEC000
  region: flash_primary
  size: 0x1000

storage:
  address: 0xEC000
  end_address: 0xF4000
  region: flash_primary
  size: 0x8000

adafruit_boot:
  address: 0xF4000
  end_address: 0x100000
  region: flash_primary
  size: 0xC000
```
This setup generates both zephyr.hex and merged.hex with the correct addresses. However, **it does not automatically generate a .merged.uf2 file** (although it still generates the zephyr.uf2.
**We need to manually run** zephyr/scripts/build/uf2conv.py **to convert the merged.hex file into a merged.uf2 file** suitable for flashing via the Adafruit bootloader both MCUBOOT + Application.

**Scenario 3: No MCUBOOT and Sysbuild**
When using Sysbuild without MCUBOOT, Zephyr ignores the board’s .dts partitions and places the application at 0x00000, which is incompatible with the Adafruit bootloader (it expects to jump to 0x27000).

To fix this, I added the following pm_static.yml:
```yaml
sd_partition:
  address: 0x00000
  end_address: 0x27000
  region: flash_primary
  size: 0x27000

app:
  address: 0x27000
  end_address: 0xEC000
  region: flash_primary
  size: 0xC5000  # from 0x27000 to 0xEC000

storage:
  address: 0xEC000
  end_address: 0xF4000
  region: flash_primary
  size: 0x8000

adafruit_boot:
  address: 0xF4000
  end_address: 0x100000
  region: flash_primary
  size: 0xC000
```
This configuration generates a merged.hex with the application correctly placed at 0x27000. Again, no merged.uf2 is automatically generated, but a manual conversion using uf2conv.py works correctly.

**Scenario 4: MCUBOOT and Sysbuild**
By reusing the same pm_static.yml from Scenario 2 and manually generating the merged.uf2, the boot process works as expected.

**My thoughts**
According to the NCS 3.0.0 release notes, Nordic intends to support only Sysbuild going forward.
Therefore, it’s important to ensure compatibility between Sysbuild and third-party bootloaders like Adafruit UF2.

As shown above, with the right pm_static.yml, it is indeed possible to make the Adafruit UF2 bootloader coexist with Sysbuild and/or MCUBOOT.

The main limitation is the lack of automatic generation of the proper final .uf2 in Scenarios 2, 3, and 4.
This prevents the use of a simple west flash -d build -r uf2 workflow.

I'd appreciate any insights or suggestions on how and where this UF2 generation could be fixed or improved.
