### ISSUE TITLE
Add ability to specify min_ram per architecture to testcase.yaml and Twister

### ISSUE THREAD

**Issue by laurenmurphyx64** [zephyrproject-rtos/zephyr#89117]
**Is your enhancement proposal related to a problem? Please describe.**
To run tests for the LLEXT subsystem, QEMU ARM boards require a min_ram of 172. As a result, our testcase.yaml has a common: min_ram: 172. Unfortunately, this filters out all the QEMU ARC boards, which have a RAM of 128, even though they can successfully run the tests.

(EDIT: Below bandaid doesn't work, see next EDIT for why)

The only way to set min_ram that I see from a quick look through the codebase is per test, or for all tests (in common). Therefore, to fulfill the need to have a different min_ram for ARM and ARC, I will have to duplicate every test in the testcase.yaml, like this:

```
  llext.readonly:
    arch_allow:               # Xtensa needs writable storage
      - arm
      - riscv
    filter: not CONFIG_MPU and not CONFIG_MMU
    extra_conf_files: ['no_mem_protection.conf']
    extra_configs:
      - CONFIG_LLEXT_STORAGE_WRITABLE=n
  llext.readonly.arc:
    arch_allow:
      - arc
    filter: not CONFIG_MPU and not CONFIG_MMU
    extra_conf_files: ['no_mem_protection.conf']
    extra_configs:
      - CONFIG_LLEXT_STORAGE_WRITABLE=n
    min_ram: 128
```

There are 8 tests, so that would become 16.

(EDIT: This solution won't work with any integration platforms. If I add an .arc, the ARM platforms aren't running on it. If I add an ARC QEMU it won't run on the non-ARC tests.)

**Describe the solution you'd like**
Something like:

```
common:
  arch:
     arc:
       min_ram: 128
```

But whatever works best to solve the problem (if you think this is a problem that needs to be fixed)

**Describe alternatives you've considered**
See above example.
