### ISSUE TITLE
testsuite: boards: unit_testing: 32-bit time_t incompatible with all other platforms

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/zephyr#90029]
**Describe the bug**

While creating some additional utilities for dealing with time structures, and using the `unit_testing` board (since that is the least expensive of all of our test platforms), I was triggering an unexpected assertion.

Namely:

```cpp
BUILD_ASSERT(sizeof(((struct timespec *)0)->tv_sec) == sizeof(int64_t), "tv_sec must be 64-bit");
```

Just to be sure that this was out of the ordinary, I created a testsuite to check that `time_t` was 64-bit on all other platforms (see 'Additional Context'), and sure enough, every other architecture that is supported by Zephyr supports a 64-bit `time_t`, even `native_sim/native`, which is the 32-bit variant of `native_sim`.

I realize it's a bit tricky due to the current `-m32` CFLAG, and what that might imply for the host platform in terms of other standard C types if we were to move to `-m64` instead.

However, we typically do want to test both 64-bit and 32-bit platforms with our `unit_testing` platform, and for the most part, standard C types should be compatible between our `unit_testing` platform and all other Zephyr platforms.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? `unit_testing`
 - What have you tried to diagnose or workaround this issue? Compared with every other architecture supported by Zephyr
 - Is this a regression? Unsure

**To Reproduce**
1. apply patch below
2. `twister -i -p unit_testing -T tests/unit/timeutil`
3. See error
4. run contrived non-unit-testing testsuite below
5. See success (inconsistence) 

**Expected behavior**
That standard C types should be consistent between the `unit_testing` platform and all other platforms in Zephyr.

**Impact**
The impact to the utilities and testsuite that I'm working on is pretty big, since it should cover most possible values within the `[INT64_MIN, INT64_MAX]` range, but without the support of the `unit_testing` platform itself, 

**Logs and console output**
```shell
In file included from /home/cfriedt/zephyrproject/zephyr/include/zephyr/toolchain.h:52,
                 from /home/cfriedt/zephyrproject/zephyr/include/zephyr/sys/printk.h:11,
                 from /home/cfriedt/zephyrproject/zephyr/subsys/testsuite/ztest/include/zephyr/ztest.h:37,
                 from /home/cfriedt/zephyrproject/zephyr/tests/unit/timeutil/test_timespec.c:12:
/home/cfriedt/zephyrproject/zephyr/include/zephyr/toolchain/gcc.h:87:36: error: static assertion failed: "tv_sec must be 64-bit"
   87 | #define BUILD_ASSERT(EXPR, MSG...) _Static_assert((EXPR), "" MSG)
      |                                    ^~~~~~~~~~~~~~
/home/cfriedt/zephyrproject/zephyr/include/zephyr/sys/timespec_util.h:23:1: note: in expansion of macro ‘BUILD_ASSERT’
   23 | BUILD_ASSERT(sizeof(((struct timespec *)0)->tv_sec) == sizeof(int64_t), "tv_sec must be 64-bit");
```

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK v0.17.0
 - Commit SHA: 4512cbf509ccbe4e54a956d3f821664062c9c408

**Additional context**
basic `testcase.yml` for the `unit_testing` platform and the `test_timeutil.c` below (and added to `tests/unit/timeutil/CMakeLists.txt`).

`tests/unit/timeutil/test_timeutil.c`:
```cpp
BUILD_ASSERT(sizeof(((struct timespec *)0)->tv_sec) == sizeof(int64_t), "tv_sec must be 64-bit");
```

When the same `.c` file is run through a non-`unit_testing` testsuite with the `testcase.yml` file below, all other platforms pass.

`testcase.yaml`
```yaml
common:
  filter: not CONFIG_NATIVE_LIBC
  tags:
    - libc
  # 1 tier0 platform per supported architecture
  platform_key:
    - arch
    - simulation
tests:
  libraries.time_t.size: {}
  libraries.time_t.size.armclang_std_libc:
    toolchain_allow: armclang
    extra_configs:
      - CONFIG_ARMCLANG_STD_LIBC=y
  libraries.time_t.size.arcmwdtlib:
    toolchain_allow: arcmwdt
    extra_configs:
      - CONFIG_ARCMWDT_LIBC=y
  libraries.time_t.size.minimal:
    extra_configs:
      - CONFIG_MINIMAL_LIBC=y
  libraries.time_t.size.newlib:
    filter: TOOLCHAIN_HAS_NEWLIB == 1
    extra_configs:
      - CONFIG_NEWLIB_LIBC=y
  libraries.time_t.size.picolibc:
    tags: picolibc
    filter: CONFIG_PICOLIBC_SUPPORTED
    extra_configs:
      - CONFIG_PICOLIBC=y
```
