### ISSUE TITLE
General board revision overlay files not applied

### ISSUE THREAD

**Issue by vbartak** [zephyrproject-rtos/zephyr#90160]
**Describe the bug**

When both qualifiers and revision is used for building app for a specific board, `<board>_<revision>.overlay` file is not found when board qualifiers are used. This does not match with the [documentation](https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#board-revision-configuration-adjustment), which states `<board>_<revision>.overlay` file should be applied regardless of qualifiers.

**To Reproduce**

1. add revisions to any board, e.g. with rpi_pico2 `boards/raspberrypi/rpi_pico2/board.yml` modified to:
```
board:
  name: rpi_pico2
  full_name: Raspberry Pi Pico 2
  vendor: raspberrypi
  revision:
    format: "number"
    default: "2"
    exact: true
    revisions:
      - name: "1"
      - name: "2"

  socs:
  - name: rp2350a
```
2. add `rpi_pico2_2.overlay` file into `boards/raspberrypi/rpi_pico2`
3. build sample blinky application for `rpi_pico2/rp2350a/m33`, .overlay file is not found

**Expected behavior**

.overlay file tied to board of specific revision should be found and added to build configuration regardless of qualifiers.

**Impact**

It is not possible to configure devicetree properties which depend on specific board revision but are independent of qualifiers. Not matching with documentation.

**Logs and console output**

**Environment (please complete the following information):**

 - OS: Ubuntu 24
 - Toolchain Zephyr SDK 16.8
 - Commit: 05c7fadf959

**Additional context**

It seems cmake only loads .overlays which directly match with loaded .dts file, in this example that is `rpi_pico2_rp2350a_m33.dts`. That means file `rpi_pico2_rp2350a_m33_2.overlay` is found and loaded correctly. However if both .overlay files are present, they should be merged and used both.
