### ISSUE TITLE
Doc: `soc.yml` has key as `cpuclusters`, not `cpucluster` in the doc

### ISSUE THREAD

**Issue by sprhawk** [zephyrproject-rtos/zephyr#91192]
### Describe the bug

The example in [doc](https://docs.zephyrproject.org/latest/hardware/porting/soc_porting.html#write-your-soc-yaml) 
should use `cpuclusters` instead of `cpucluster`:
```yaml
family:
  name: <family-name>
  series:
    - name: <series-1-name>
      socs:
        - name: <soc1>
          cpuclusters:
            - name: <coreA>
            - name: <coreB>
              ...
        - name: <soc2>
    - name: <series-2-name>
      ...
```

### Regression

- [ ] This is a regression.

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.
