### ISSUE TITLE
doc: DT: use-prop-name is not documented

### ISSUE THREAD

**Issue by SebastianBoe** [zephyrproject-rtos/zephyr#9971]
The file device_node.yaml.template is a big help in understanding how to read and write the "YAML definitions for device nodes". But it does not cover the keyword 'use-prop-name'.

Currently, a user would have to read the python code to understand it's semantics.

Documentation:

```
# A typical property entry will look like the following
#   <name of property as it is in device tree>
#     category: <required | optional>
#     type: <string | int | array>
#     description: <description of property>
#     generation: <define | structure>
```

Actual language:

```
    cs-gpios:
      type: compound
      category: optional
      generation: define, use-prop-name
```
